### ISSUE TITLE
 I try to use the GPU  , check for missing files ,"onnxruntime_providers_cuda.dll"

### ISSUE THREAD

**Issue by shr545980981** [microsoft/onnxruntime#10015]
Where can I get this file“onnxruntime_providers_cuda.dll”？please

[E:onnxruntime:ort-java, provider_bridge_ort.cc:995 onnxruntime::ProviderLibrary::Get] LoadLibrary failed with error 126 "**************" when trying to load "C:\*****\AppData\Local\Temp\onnxruntime-java11575941624071955757\onnxruntime_providers_cuda.dll"
ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: OrtSessionOptionsAppendExecutionProvider_Cuda: Failed to load shared library

**Comment by Craigacp** [comment]
Use `onnxruntime_gpu` to use the GPU in the Java API - https://search.maven.org/artifact/com.microsoft.onnxruntime/onnxruntime_gpu/1.10.0/jar.

**Comment by shr545980981** [comment]
![image](https://user-images.githubusercontent.com/96031961/145911855-01212c40-c25d-4099-8b80-f245c1bf35df.png)



> 用于`onnxruntime_gpu`在 Java API 中使用 GPU - https://search.maven.org/artifact/com.microsoft.onnxruntime/onnxruntime_gpu/1.10.0/jar。

**Comment by shr545980981** [comment]
I tried to run and found that ONNX would create a temporary folder，such as "onnxruntime-java10192008397122486566" ，but “onnxruntime_providers_cuda.dll” does not exist in this folder .  
![image](https://user-images.githubusercontent.com/96031961/145912695-d8a577f3-3ab2-4eab-a0ce-3373d32a46e0.png)

**Comment by shr545980981** [comment]
Error code 

![image](https://user-images.githubusercontent.com/96031961/145912975-fb789bec-adef-4c6b-bbc9-ea0c6f64c9c4.png)


(Inference.java:1578):
![image](https://user-images.githubusercontent.com/96031961/145913050-049495ec-c5a0-44ae-af86-aa908a8e4a21.png)

**Comment by shr545980981** [comment]
Has been resolved ~ the error code when running in IDEA . But I can use the GPU when running in the JAR

**Comment by ytaous** [comment]
Close it for now, pls reopen as needed.

**Comment by mike-burl** [comment]
I'm running into this issue and it's also still not working when I attempt to run the generated jar file.  I'm seeing that the correct cuda dll file is being generated in the temp directory, however my jar still doesn't seem to be able to recognize it

**Comment by Craigacp** [comment]
Are you compiling from source, or using the Maven artifacts? If the former check if the jar file contains the `onnxruntime_providers_cuda.dll` file. If the latter, maybe you don't have the right version of CUDA & cuDNN installed? That error could be triggered by it failing to load a library `onnxruntime_providers_cuda.dll` depends on as well.

**Comment by mike-burl** [comment]
Thanks for the quick response!  This is what I have in my build.gradle:
`implementation 'com.microsoft.onnxruntime:onnxruntime_gpu:1.10.0'`
and this is my cuda version:
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Thu_Feb_10_19:03:51_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.112
Build cuda_11.6.r11.6/compiler.30978841_0
```

The only thing I can possibly see is that my CUDA install is on 11.6 while the documentation asks for 11.4, however I didn't think that was an issue as the documentation says it should be compatible with any 11.x version.  Should I roll back to 11.4?

**Comment by Craigacp** [comment]
Can you check to see if the Python GPU binary loads properly on your machine? One other thing to check is that you've got cuDNN in an accessible place. I'm not entirely sure what the CUDA/cuDNN requirements are, but it is checked in the CI for both Python and Java so it should work if you've got the paths & versions right.

**Comment by mike-burl** [comment]
Yup turns out my installation of cuDNN was incorrect.  Wiping that out and reinstalling fixed the issue.  Thank you!
