### ISSUE TITLE
ONNXOptimizer: ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2215158499

### ISSUE THREAD

**Issue by michaelroyzen** [microsoft/onnxruntime#12359]
@yufenglee I'm not sure this issue is fixed (tried using the latest onnxruntime-1.12.0 GPU). While disabling shape inference works for quantization, optimization is still broken for saving models such as albert-xxl. The issue seems to be that [write_external_data_tensors](https://github.com/onnx/onnx/blob/529f7cab88eed143fc9f0126147e9732585e4c5e/onnx/__init__.py#L195) isn't actually respecting the condition when it's set to true:

> Traceback (most recent call last):
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 525, in <module>
    main()
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 311, in main
    optimizer.export(
  File "/home/mroyzen/train_files/optimum/optimum/onnxruntime/optimization.py", line 149, in export
    optimizer.save_model_to_file(onnx_optimized_model_output_path, use_external_data_format=True)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 934, in save_model_to_file
    save_model(self.model, output_path)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 202, in save_model
    s = _serialize(proto)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 71, in _serialize
    result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2215158499

Your help would be appreciated. [Linking to my issue](https://github.com/huggingface/optimum/issues/222) in Huggingface's Optimum library, but everything seems to be working on their end as evidenced by the stack trace.

Your help would be appreciated. Thanks

_Originally posted by @michaelroyzen in https://github.com/microsoft/onnxruntime/issues/11072#issuecomment-1197711143_

**Comment by michaelroyzen** [comment]
I suspect that the issue is that 

> /opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py

is an outdated file -- it seems that the onnx_model.py path needs to be fixed somewhere, seemingly in this import:

> from onnxruntime.transformers.optimizer import optimize_model

as that is where _save_model_to_file_ is imported, which than calls onnx_model.py at the above path.

**Comment by tianleiwu** [comment]
@michaelroyzen, could you uninstall onnxruntime-gpu, then install the nightly build
``
pip install -i https://test.pypi.org/simple/ ort-nightly-gpu
``
I guess the issue is resolved in the master branch, since I did not see problem in saving >2GB model file.

**Comment by michaelroyzen** [comment]
Thanks for your response, but using the nightly build did not solve this issue @tianleiwu. The issue is that the `from onnxruntime.transformers.optimizer import optimize_model` seems to load some legacy file:

> /opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py

**Comment by tianleiwu** [comment]
@michaelroyzen, I think the onnx_model.py file shall be updated when you install nightly build.

**Comment by michaelroyzen** [comment]
@tianleiwu You're right that onnx_model.py is updated, but model saving is still broken. I added a sanity check in `save_model_to_file`:

`print(use_external_data_format)
OnnxModel.save(self.model, output_path, use_external_data_format, all_tensors_to_one_file)`

which correctly prints True, and yet I still get 

> True
Traceback (most recent call last):
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 525, in <module>
    main()
  File "examples/onnxruntime/optimization/question-answering/run_qa.py", line 311, in main
    optimizer.export(
  File "/home/mroyzen/train_files/optimum/optimum/onnxruntime/optimization.py", line 150, in export
    optimizer.save_model_to_file(onnx_optimized_model_output_path, use_external_data_format=True)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 938, in save_model_to_file
    OnnxModel.save(self.model, output_path, use_external_data_format, all_tensors_to_one_file)
  File "/opt/conda/lib/python3.8/site-packages/onnxruntime/transformers/models/gpt2/../../onnx_model.py", line 914, in save
    save_model(
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 202, in save_model
    s = _serialize(proto)
  File "/opt/conda/lib/python3.8/site-packages/onnx/__init__.py", line 71, in _serialize
    result = proto.SerializeToString()
ValueError: Message onnx.ModelProto exceeds maximum protobuf size of 2GB: 2215158447

**Comment by tianleiwu** [comment]
@michaelroyzen, I think you are using older verison of onnx. Try upgrade onnx to the latest version `pip install onnx --upgrade`
If it reproduces with latest onnx version, I think you can fill an issue in https://github.com/onnx/onnx.

**Comment by michaelroyzen** [comment]
Tried with those dependencies @tianleiwu and still the same error. Will open up an issue in onnx.
