### ISSUE TITLE
Issue finding onnxruntime dll

### ISSUE THREAD

**Issue by oliver-bernhardt** [microsoft/onnxruntime#15375]
### Describe the issue

Hi

We are facing an issue with onnxruntime in our C# application. Usually, everything works just fine on any type of Windows 10 x64 platform. However for some reason (that is not clear to me) we get this exception 

 **The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception.
System.EntryPointNotFoundException: Unable to find an entry point named 'OrtGetApiBase' in DLL 'onnxruntime'.**

on this system:

Edition  Windows 10 Enterprise LTSC
Version 21H2
Installed on         ‎24/‎03/‎2023
OS build               19044.2728
Experience         Windows Feature Experience Pack 120.2212.4190.0
Processor           Intel(R) Xeon(R) W-2295 CPU @ 3.00GHz   3.00 GHz
Installed RAM    128 GB (128 GB usable)
System type       64-bit operating system, x64-based processor

By default, the ddls are stored in the subfolder "bin\runtimes\win-x86" and "bin\runtimes\win-x64".
I also tried moving them into the same folder as the main executable without any change.

I need to point out that this was never a problem on Windows 10 Professional so I wonder whether you know anything to be special in this environment? 

Is there anything else that could cause this issue? Any idea on how I could further investigate the problem?

Oli

### To reproduce

I currently don't know whether it is reproducible as I only have 1 system with this setup on which it does happen.

### Platform

Windows

### OS Version

Windows 10 Enterprise LTSC, Version 21H2, 19044.2728

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.12.1

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Default CPU

**Comment by baijumeswani** [comment]
I found a similar issue reported earlier and saw some solutions posted by users: https://github.com/microsoft/onnxruntime/issues/9260.

Were you able to try those out? Let me know if any of those worked for you.

**Comment by oliver-bernhardt** [comment]
Hey

Thanks for pointing it out. However, I don't think this is the same issue. In our case, it works pretty much every (hundreds of installations on Windows 10 without any issue). But somehow, on that particular system it does not work (same build of the software using the same installer and everything).

I will try the solution that was provided in that thread but I doubt it will change anything. It will take a while till I know for sure as I have to indirectly troubleshoot it as I can not reproduce the problem (it's a user that reported the issue on his machine).

Oli

**Comment by snnn** [comment]
> In our case, it works pretty much every (hundreds of installations on Windows 10 without any issue). But somehow, on that particular system it does not work (same build of the software using the same installer and everything).

Do all the Win10 have the same version?

**Comment by baijumeswani** [comment]
@oliver-bernhardt would you please share with us the logs you're seeing for the dlls being loaded. You will need to put your program into a debugger to get those logs.

Please see @snnn's [comment](https://github.com/microsoft/onnxruntime/issues/14003#issuecomment-1355590926) for an example on how to do this.

**Comment by yuslepukhin** [comment]
This can happen when the library that is found is loaded from the System folder, which is almost always the wrong version. If you ship onnxruntime dll side by side with your executable, it would never happen.

**Comment by ihtfw** [comment]
I faced same problem for net472 and problem was that onnxruntime.dll wasn't copied to output. To fix this I had to specify  runtime identifier explicitly like this in exe csproj:
  <PropertyGroup>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

**Comment by jamesd-ms** [comment]
Hello, seeing similar exception in the released v1.15.0 https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime/1.15.0

**System.TypeInitializationException: The type initializer for 'Microsoft.ML.OnnxRuntime.NativeMethods' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'onnxruntime' or one of its dependencies: The specified procedure could not be found. (0x8007007F) 
at Microsoft.ML.OnnxRuntime.NativeMethods.OrtGetApiBase() 
at Microsoft.ML.OnnxRuntime.NativeMethods..cctor()**

No such error previously when using older version; even a v1.15.0-dev version is working fine.

**Comment by yuslepukhin** [comment]
Check how many `onnxruntime.dll`s you have on the system and see which one is being loaded. Quick check is to open a command line and do `where onnxruntime.dll` and see which one shows up.

Check [this.](https://github.com/microsoft/onnxruntime/issues/13658)

**Comment by skottmckay** [comment]
@jamesd-ms can you provide a minimal sln and csproj that repros the issue? AFAIK nothing changed in the structure of the native nuget package recently that would change where it looks for onnxruntime.dll. 

For most .net targets I would expect it's using the netstandard2.0 (lowest common denominator for the ORT native package) props. e.g. for x64 that would mean linking onnxruntime.dll from runtimes\win-x64\native in the nuget package.

<img width="626" alt="image" src="https://github.com/microsoft/onnxruntime/assets/979079/6fc50f4d-fca1-4917-85a4-f07a5b58076c">

**Comment by skottmckay** [comment]
@jamesd-ms which dev build of the package was working? can diff that vs. the release to see what changed

**Comment by snnn** [comment]
Fixed in ONNX Runtime 1.15.1 release.

**Comment by snnn** [comment]
ONNX Runtime 1.15.1 is published.

**Comment by thiennguyen99** [comment]
it still happens. I got the same exception,

Shared library 'libonnxruntime.so' not loaded, p/invoke 'OrtGetApiBase' may fail
TypeInitialization_Type, Microsoft.ML.OnnxRuntime.NativeMethods

package version: Microsoft.ML.OnnxRuntime 1.15.1
environment: Maui .Net7
Only in android arm64-v8a
App taken from distribution AppCenter Azure

**Comment by ErrorGz** [comment]
After compiling a program that uses onnxruntime, it runs fine on my local machine and also runs smoothly in common runtime environments. However, when I installed Windows 10 or Windows 11, the program failed to run. To resolve this, I installed some toolkits for vs2022 in the new system environment, and now the program runs properly. The toolkits I installed for your reference include:

Microsoft Visual C++ Redistributable
.NET 6.0 Runtime (Long-Term Support)
.NET Profiler
C++ Core Features
MSVC v143 - VS 2022 C++ x64/x86 Build Tools
Graphics Debugger and GPU Profiler for DirectX
C++ Profiler
Please note that the above information and translations may not perfectly match the original English version, as I used a Simplified Chinese environment for installation and gathering information.

**Comment by aib** [comment]
There's a filename mismatch—native code searches for `onnxruntime.DLL` whereas the file is named `onnxruntime.dll`. Causes this issue in case-sensitive filesystems.

**Comment by snnn** [comment]
@aib , would you please create a new issue and provide reproduce steps?

**Comment by 1ilterhan1** [comment]
> I faced same problem for net472 and problem was that onnxruntime.dll wasn't copied to output. To fix this I had to specify runtime identifier explicitly like this in exe csproj:
> 
> ```
>   <PropertyGroup>
>     <RuntimeIdentifier>win-x64</RuntimeIdentifier>
>     <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
>   </PropertyGroup>
> ```

I’ve been struggling with this problem for 5 hours, and this finally solved it for me — thank you so much!

**Comment by aib** [comment]
For the record, the case-sensitive filename issue was reported in #26129 and fixed in #26415.
