### ISSUE TITLE
ort_perf_view tool doesn't load any profiling data

### ISSUE THREAD

**Issue by Apisteftos** [microsoft/onnxruntime#16873]
### Describe the issue

I am trying to visualize my inferenced profiling data and load it with this tool but seems, doesn't load anything.  

### To reproduce

- Loading profiling data from the same directory or different with ort_perf_view tool
- Tested with profiling data from onnxruntime and browser doesn't load any statistics data. It just remains blank. 

### Platform

Linux

### OS Version

Ubuntu 22.04

### ONNX Runtime Installation

pip installation

### ONNX Runtime Version or Commit ID

1.15.0

### ONNX Runtime API

Python

### Architecture

X64

### Execution Provider

CUDA

**Comment by Apisteftos** [comment]
Sure, I attached  two profile data. It would be nice to see if this tool actually works. 

[onnxruntime_profile__2023-07-27_01-1.zip](https://github.com/microsoft/onnxruntime/files/12181772/onnxruntime_profile__2023-07-27_01-1.zip)

**Comment by Red-Eyed** [comment]
Hello, I have similar error. Profiling data is shown in perfetto/edge://tracing
![image](https://github.com/microsoft/onnxruntime/assets/11485451/22afd9c9-f53b-4f69-9f94-c56e8282e64d)

**Comment by Red-Eyed** [comment]
Fixed it
In this line:
`<script src="https://cdn.anychart.com/releases/8.11/js/anychart-ui.min.js"></script>`
change `8.11` -> `8.11.1`

**Comment by Apisteftos** [comment]
Yes the problem was in the anychart: 

What I did: 

- cd /path/ to / ort_perf_view.html
- open a local server with  python -m http.server and browser: http://localhost:8000/ort_perf_view.html
- With google chrome go to the console and the problem was:
```
anychart-ui.min.js:57 Uncaught TypeError: Cannot read properties of undefined (reading 'prototype')
    at anychart-ui.min.js:57:333
    at anychart-ui.min.js:120:488
    at anychart-ui.min.js:10:409
    at anychart-ui.min.js:10:440
```
So it just need to replace the release version. Here is the correct code:

```
  <script type="text/javascript" src="https://cdn.anychart.com/releases/v8/js/anychart-core.min.js"></script>
  <script src="https://cdn.anychart.com/releases/8.11.1/js/anychart-ui.min.js"></script>
  <script type="text/javascript" src="https://cdn.anychart.com/releases/v8/js/anychart-treemap.min.js"></script>
  <link rel="stylesheet" type="text/css" href="https://cdn.anychart.com/releases/8.11.1/css/anychart-ui.min.css"/>

```

**Comment by kubaraczkowski** [comment]
Hm seems to be still broken, updating to version 8.12.1 works
