### ISSUE TITLE
could not find OpenMP_C when I build 

### ISSUE THREAD

**Issue by WilliamZhaoz** [microsoft/onnxruntime#2044]
when I run 
./build.sh --config RelWithDebInfo --use_mkldnn --build_wheel --parallel
I get:
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS)
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS)
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Could NOT find Threads (missing: Threads_FOUND)
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.6.8", minimum required is "3.5")
CMake Error at /usr/local/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
Could NOT find Threads (missing: Threads_FOUND)

my cmake version is 3.15

**Comment by jywu-msft** [comment]
in https://github.com/microsoft/onnxruntime/issues/2046 , you mentioned the command succeeded.
does it mean your issue is resolved?

**Comment by WilliamZhaoz** [comment]
actually, I did not solved it, and then I move to another pc, and then I
change the CMakelist.txt, add something to find the OpenMP then it work,
but in another PC, it can not work.

George Wu <notifications@github.com> 于2019年10月9日周三 上午12:04写道：

**Comment by faxu** [comment]
It sounds like it may be some specific environment issue. Do you need further assistance from the core ONNX Runtime team?

**Comment by WilliamZhaoz** [comment]
yes, it is a specific env issue, and now I am working on another machine.
so let it go.
thanks you for your help.

Faith Xu <notifications@github.com> 于2019年10月22日周二 上午5:18写道：
