### ISSUE TITLE
GENERAL ERROR : GSL: Precondition failure at /onnxruntime_src/cmake/external/gsl/include/gsl/span: 475

### ISSUE THREAD

**Issue by HarryVancao** [microsoft/onnxruntime#2154]
**Describe the bug**
I am running a simple model with the following architecture: 

input -> MaxPool -> MaxUnpool -> output 

The maxpool has a kernel_size and stride of 2 whereas the input has a shape of 45x45. The MaxUnpooling operation uses the third output_size input 

my intended shapes are:
45x45 -> 22x22 -> 45x45

However, when I run this small model, I get the following error:
RuntimeError: Method run failed due to: [ONNXRuntimeError] : 1 : GENERAL ERROR : GSL: Precondition failure at /onnxruntime_src/cmake/external/gsl/include/gsl/span: 475

which is not exactly clear. I believe that this is a valid graph so I am not sure if this is a bug in ONNX Runtime or in the model itself. 

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 9
- ONNX Runtime installed from (source or binary): binary
- ONNX Runtime version: 0.4.0
- Python version: 3.5.3
- Visual Studio version (if applicable):
- GCC/Compiler version (if compiling from source):
Running in CPU provider
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
I am attaching the ONNX file and a reproduction script to this issue: [runSpanError.zip](https://github.com/microsoft/onnxruntime/files/3740645/runSpanError.zip)

**Expected behavior**

**Screenshots**

**Additional context**
Add any other context about the problem here. If the issue is about a particular model, please share the model details as well to facilitate debugging.

**Comment by pranavsharma** [comment]
Can you try one of our nightly python pkgs? We'll be releasing a new version of onnxruntime (1.0) soon (in the next 2 weeks) and it'll be better to use the latest version. I tried the nightly and didn't see this error.

```
PS C:\Users\prs\Downloads> pip install -i https://test.pypi.org/simple/ ort-nightly                                                                                         Looking in indexes: https://test.pypi.org/simple/
Collecting ort-nightly
  Downloading https://test-files.pythonhosted.org/packages/36/16/3313e89998da7227663aa87ed23c09809e4f8e2ec342a4d3f71a7ba57207/ort_nightly-0.5.0.dev1015-cp37-cp37m-win_amd64.whl (2.3MB)
    100% |████████████████████████████████| 2.3MB 4.5MB/s
Installing collected packages: ort-nightly
Successfully installed ort-nightly-0.5.0.dev1015
You are using pip version 19.0.3, however version 19.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
PS C:\Users\prs\Downloads> python .\runSpanError.py                                                                                                                         [array([[[[0.9721882 , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.88615507,
          0.        , 0.        ],
         [0.8540868 , 0.        , 0.98478407, ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.        , 0.        , 0.37845156, ..., 0.        ,
          0.9791654 , 0.        ],
         [0.        , 0.        , 0.94048285, ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.7656365 , ..., 0.9990739 ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.75793755, ..., 0.        ,
          0.        , 0.        ],
         ...,
         [0.80659443, 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.7475449 , 0.5869437 , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]],

        [[0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ],
         [0.        , 0.71590453, 0.88607764, ..., 0.        ,
          0.98689175, 0.        ],
         ...,
         [0.        , 0.        , 0.6778235 , ..., 0.69493437,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.7661256 ,
          0.        , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          0.        , 0.        ]]]], dtype=float32)]
```

**Comment by HarryVancao** [comment]
It seems that the nightly build works on my end. I will close this issue. 

If you happen to know which commit resolves this problem, could you point me to the commit?

**Comment by skottmckay** [comment]
I think this is just masked in later releases as some bounds checking is turned off in release builds.

Looking into it. Possibly related to https://github.com/onnx/onnx/issues/2398

**Comment by skottmckay** [comment]
Fixed in master.

**Comment by HarryVancao** [comment]
Hi, can we re-open this issue? 

I am still getting this error in ONNX Runtime. despite the fix. I tried running this in the nightly onnx runtime and in the released onnx runtime 1.1. I am attaching the file in question. Can you please confirm whether or not this is a bug? I believe that this is a valid ONNX file. 

[bug.zip](https://github.com/microsoft/onnxruntime/files/4370496/bug.zip)
