### ISSUE TITLE
[Web] The ONNX model cannot be loaded via WASM in the IOS17 browser.

### ISSUE THREAD

**Issue by zyhhahah** [microsoft/onnxruntime#22086]
### Describe the issue

This is the encountered error, which only occurs in the web environment on the iPhone.
![Snipaste_2024-09-13_11-14-25](https://github.com/user-attachments/assets/20538ba1-5f46-4250-93fc-00416811062a)
I initially thought this issue was caused by version differences, so I tried many versions. They all worked fine in the web environment on Android and Windows. Based on the error message, it seems to be caused by insufficient memory. I tried many different models, including some very small ones, but the issue persisted. However, I found that when using the WebGL backend, the issue does not occur. It only happens with the WASM backend.

### To reproduce

In my project, the code is quite complex, so I simplified it following the official example to reproduce the issue. The model used can be any ONNX model. The devices I tested on include iPhone 13 Pro, iPhone 13 Pro Max, and iPhone 15 Pro Max, and the issue occurred on all of them.
![image](https://github.com/user-attachments/assets/4bb90327-8eff-4695-ae80-ef5fad5b4dbd)

### Urgency

My project is currently at a standstill due to this issue, and I'm not sure whether it's a problem with my implementation or a version-related issue. I'm wondering if I'm the only one encountering this problem.

### ONNX Runtime Installation

Built from Source

### ONNX Runtime Version or Commit ID

多版本都存在这个问题

### Execution Provider

'webgl' (WebGL), 'wasm'/'cpu' (WebAssembly CPU)

**Comment by transcranial** [comment]
We are also seeing this exact error with onnxruntime-web 1.19.0, running a tiny model in all browser on iOS 17.6.1 as well as iPadOS 17.6.1. Works fine in all browsers including safari on macOS. Downgrading onnxruntime-web to 1.18.0 fixes this for us.

**Comment by satyajandhyala** [comment]
The Out of Memory error was previously reported and fixed by rolling back Emscripten SDK upgrade, backe to 3.1.59. Did reproduce this error with the latest code on main branch?

**Comment by zyhhahah** [comment]
> 我们在 onnxruntime-web 1.19.0 中也看到了同样的错误，在 iOS 17.6.1 和 iPadOS 17.6.1 上的所有浏览器中运行了一个小模型。在包括 macOS 上的 Safari 在内的所有浏览器中都可以正常工作。将 onnxruntime-web 降级到 1.18.0 可以为我们解决这个问题。

Thank you for your help. The issue indeed doesn't exist in version 1.18.0, it seems I carelessly missed this during my earlier attempts. I really appreciate your reminder.

**Comment by zyhhahah** [comment]
> 之前曾报告过内存不足错误，并通过将 Emscripten SDK 升级回滚到 3.1.59 来修复。是否使用主分支上的最新代码重现了此错误？

Hello, I tried using the latest code as per your suggestion. Unfortunately, the same error still occurs.

**Comment by fs-eire** [comment]
@zyhhahah could you help to test whether the following versions work or not:
- 1.20.0-dev.20240919-bd60add8ce
- 1.19.2
- 1.18.0

**Comment by zyhhahah** [comment]
@fs-eire I tested these three versions on various platforms.

- 1.20.0-dev.20240919-bd60add8ce ==> on iOS system no available backend found. ERR: [wasm] RangeError: Out of memory

- 1.19.2 ==> on iOS system no available backend found. ERR: [wasm] RangeError: Out of memory

- 1.18.0 ==>  success 

- 1.18.0 ==>  But there's one thing I'm not sure is a potential issue: when I enable crossOriginIsolated mode, my iPhone still encounters an out-of-memory problem, and it only runs normally when I manually set wasm.numThreads to 1. wasm.numThreads cannot be set to the default value or a number greater than 1.

**Comment by fs-eire** [comment]
I think this is a known issue of Safari and it is fixed in iOS v18.0: https://github.com/emscripten-core/emscripten/issues/19374

Screenshot from BrowserStack - https://jsfiddle.net/tpz1k9d7/3/

iOS 17:
![image](https://github.com/user-attachments/assets/ae00192c-27ee-4105-a94e-988b0a7b2870)

iOS 18:
![image](https://github.com/user-attachments/assets/ddd9ea5f-dfc1-4b5e-9f0e-af02daca9b0c)

**Comment by zyhhahah** [comment]
@fs-eire Thank you for your reminder. I have also tested it and confirmed that indeed in iOS 18 this issue does not occur, so my question can be closed.

**Comment by ohnobug** [comment]
work for me

```
import * as ort from 'onnxruntime-web';
ort.env.wasm.wasmPaths = "https://cdnjs.cloudflare.com/ajax/libs/onnxruntime-web/1.18.0/"
ort.env.wasm.simd = false;
ort.env.wasm.numThreads = 1;
ort.env.debug = true;
```

**Comment by jayanth0107** [comment]
@ohnobug resource not found for wasmPath provided above - https://cdnjs.cloudflare.com/ajax/libs/onnxruntime-web/1.17.3/

**Comment by ohnobug** [comment]
@jayanth0107 or use https://cdn.jsdelivr.net/npm/onnxruntime-web@1.17.3/dist/ort.min.js

package page:
https://www.jsdelivr.com/package/npm/onnxruntime-web?version=1.17.3

**Comment by fs-eire** [comment]
Yes, you can use jsdelivr which still have version 1.17.3 available.

By the way, onnxruntime-web no longer release webassembly artifacts for non-SIMD and non-MultiThread since version 1.18. While you can use onnxruntime v1.17.3 as a compatibility workaround for ios17.

**Comment by jbrough** [comment]
This has has reoccurred in the 1.22.0 release

**Comment by fs-eire** [comment]
@jbrough could you describe it more about "issue has reoccurred in the 1.22.0 release"? Is it v1.21.1 working but v1.22.0 not working on a specific iOS version ?

**Comment by jbrough** [comment]
@fs-eire yes, sorry I tried to find this thread again to provide more info.  v1.21.1 worked. v1.22.0 does not on iOS (v18), when the cdn switched it out a few days ago, that's when I noticed the issue:  OOM Range Error, as above.

Compiling to wasm myself with these flags fixes it on Safair IOS18

```
onnxruntime_EMSCRIPTEN_SETTINGS="MALLOC=dlmalloc;STACK_SIZE=1048576;INITIAL_MEMORY=67108864;ALLOW_MEMORY_GROWTH=1;MAXIMUM_MEMORY=201326592"
```

I think if I went much above 196MB max shared memory the bug would re-occur but I didn't test that yet,

**Comment by theopolis** [comment]
Hi @jbrough, are the updated memory limits you mention something that can be updated in ONNX itself? Such that newer releases begin working again for MobileSafari/Mobile Chrome/etc?

**Comment by ic-dc** [comment]
@theopolis I am currently trying to build wasm for onnxruntime, but following simple ./build.sh script fails, did you succeed with compilation?

**Comment by jbrough** [comment]
sorry for not checking back. Ironically I had the same issue again and accidentally found my own message as a solution.

 here how you avoid it (works on 1.26.0 tag)

```
./build.sh --config Release --build_wasm --skip_tests --enable_wasm_simd --enable_wasm_threads --cmake_extra_defines onnxruntime_EMSCRIPTEN_SETTINGS="MALLOC=dlmalloc;STACK_SIZE=1048576;INITIAL_MEMORY=67108864;ALLOW_MEMORY_GROWTH=1;MAXIMUM_MEMORY=201326592"
```

Not you do _need_ --enable_wasm_threads even if you intend to run `ort.env.wasm.numThreads = 1;` otherwise it will NOT compile-in some MBLAS float ops and the wasm build with fail at the very end of a very long compile process. 

This once again fixed OOM issues on Safari mobile - even with tiny models you will get this issue. I think because the threaded runtime reserves a lot of memory upfront, no matter what.
