### ISSUE TITLE
[Mobile]  Maui with ONNX Runtime does not compile for IOS

### ISSUE THREAD

**Issue by Assassyn** [microsoft/onnxruntime#22661]
### Describe the issue

I have a mobile application that uses OnnxRuntime to try to generate a new image. The application works on Android and Windows, but I cannot compile it for and on IOS/macOS.

I am using the Vs2022 with remote build on Mac ( INterl based but running Sequoia) 

I am getting the error : 
`
Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		clang++ exited with code 1:
ld: library 'C:/Users/<user>/.nuget/packages/microsoft.ml.onnxruntime/1.19.2/buildTransitive/net8.0-ios15.4/../../runtimes/ios/native/onnxruntime.xcframework.zip' not found
clang++: error: linker command failed with exit code 1 (use -v to see invocation)	Functional.Silhouettist.Mobile (net8.0-ios)	C:\Program Files\dotnet\packs\Microsoft.iOS.Sdk.net8.0_18.0\18.0.8303\targets\Xamarin.Shared.Sdk.targets	1643	
`

I have tried to add a native library, but it makes no difference.

`
<NativeReference` Include="dep\onnxruntime.xcframework.zip" Kind="Framework" />
`

### To reproduce

1. Create new MAUI app
2. Add OnnxRuntime
3. Try to deploy to Simulator. 

or use the repo: https://github.com/Assassyn/maui_onnx_ios_fail

### Urgency

I need it to release the application

### Platform

iOS

### OS Version

17.5 and 18

### ONNX Runtime Installation

Released Package

### Package Name (if 'Released Package')

None

### ONNX Runtime Version or Commit ID

1.19.2 but 1.18 was not working as well 

### ONNX Runtime API

C#

### Architecture

X64

### Execution Provider

Other / Unknown

**Comment by ben-dean** [comment]
I'm getting the same errors in my app having updated to MacOS 15.1, Xcode 16 and dotnet 8.0.403. 

The app is not using maui but a native net8.0-ios app.

**Comment by ben-dean** [comment]
Yes, I have updated to the latest versions.

```
 <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.20.0" />
 <PackageReference Include="Microsoft.ML.OnnxRuntime.Extensions" Version="0.13.0" />
 <PackageReference Include="Microsoft.ML.OnnxRuntime.Managed" Version="1.20.0" /> 

```

**Comment by skottmckay** [comment]
onnxruntime.xcframework.zip has an xcframework for multiple different platforms (iOS arm64, iOS simulator x64/arm64, mac-catalyst x64/arm64) and the mac-catalyst ones require the use of symlinks. As symlinks aren't supported by nuget on Windows we have to create a zip. 

I would have expected the MAUI build infrastructure to expand the zip and use the xcframework within it. if that happened clang++ should be linking against the `onnxruntime` library found at `onnxruntime.xcframework.zip/onnxruntime.xcframework/ios-arm64/onnxruntime.framework/onnxruntime` for an iOS build

Short term while we look into it you could try extracting the onnxruntime.xcframework from the zip and adding a NativeReference to that. I'd suggest copying the settings from the nuget package targets file

```xaml
  <ItemGroup Condition="('$(OutputType)'!='Library' OR '$(IsAppExtension)'=='True')">
    <NativeReference Include="<extracted>\onnxruntime.xcframework">
      <Kind>Static</Kind>
      <IsCxx>True</IsCxx>
      <SmartLink>True</SmartLink>
      <ForceLoad>True</ForceLoad>
      <LinkerFlags>-lc++</LinkerFlags>
      <WeakFrameworks>CoreML</WeakFrameworks>
    </NativeReference>
  </ItemGroup>
```

**Comment by nickrandolph** [comment]
@skottmckay any updates on this issue?

**Comment by skottmckay** [comment]
This should fix the issue: https://github.com/xamarin/xamarin-macios/pull/21492

But it's unclear how it was working originally. I still have the test setup from when I added usage of the zipped xcframework and that builds happily.

**Comment by enusbaum** [comment]
> This should fix the issue: [xamarin/xamarin-macios#21492](https://github.com/xamarin/xamarin-macios/pull/21492)
> 
> But it's unclear how it was working originally. I still have the test setup from when I added usage of the zipped xcframework and that builds happily.

Do you happen to know the appropriate path to get the new `NativeReference` working for `Microsoft.ML.OnnxRuntime`?

**Comment by syedbilalali** [comment]
> This should fix the issue: [dotnet/macios#21492](https://github.com/dotnet/macios/pull/21492)
> 
> But it's unclear how it was working originally. I still have the test setup from when I added usage of the zipped xcframework and that builds happily.

How you did you resolve it, Can you please explain it here or you can also provide some links for guidance to resolve it. I appreciate your prompt response.

**Comment by Assassyn** [comment]
I did not resolve it completely. I bought the iPhone, and I did manage to compile it for it, but I am still not able to run it on an emulator. 

As I am on holiday,  I will try the advice fix in around a week and report here if this is working.

**Comment by yuhui17** [comment]
Hi, I also getting the same error net8.0-ios15.4/../../runtimes/ios/native/onnxruntime.xcframework.zip' not found clang++: error: linker command failed with exit when build the project. 

At the end i solved by downgrading the Microsoft.ML.OnnxRuntime
to <PackageReference Include="Microsoft.ML.OnnxRuntime" Version="1.12.1" />  (sample project also use this version)

Now i able to build and work fine, hope this help.

**Comment by BlueReptile2** [comment]
Hi everyone! I worked hard and found out a solution that worked with my .NET 8.0 MAUI, kind of like Microsoft.ML.OnnxRuntime.Extensions.Dummy. I will skip right to the tutorial since I usually hate to read too much..

**Step 1 (I extracted the package from zip):**
• Go to  Microsoft.ML.OnnxRuntime nuget package folder and find the zip
C:\Users\<username>\.nuget\packages\microsoft.ml.onnxruntime\<used version 1.21.0 in my case>\runtimes\ios\native\onnxruntime.xcframework.zip

• **[IMPORTANT]** Extract the folder with right click > Extract all (the result should be ...\runtimes\ios\native\onnxruntime.xcframework\onnxruntime.xcframework\ ios-arm64 & ios-arm64_x86_64-simulator). _I am not sure if it still works if you go ahead and copy paste the folder from the zip since it will only have the 1st folder onnxruntime.xcframework not the nested one_

• **[Optional]** I also deleted the folder that had "maccatalyst" since i don't use it

**Step 2 (I manually changed .targets file):**
• Find the .target file
"C:\Users\<username>\.nuget\packages\microsoft.ml.onnxruntime\<used version>\buildTransitive\net8.0-ios15.4\Microsoft.ML.OnnxRuntime.targets"

• Open the file and change NativeReference from
<NativeReference Include="$(MSBuildThisFileDirectory)..\..\runtimes\ios\native\onnxruntime.xcframework.zip">
to
<NativeReference Include="$(MSBuildThisFileDirectory)..\..\runtimes\ios\native\onnxruntime.xcframework">

• I also changed SmartLink from True to False, not sure if it makes any difference in this case.

**_AFTER THESE STEPS I TRIED TO RUN BUT HAD ANOTHER ISSUE:_**
_clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_RegisterCustomOps", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation).

**Step 3 [This step was completely made on a Mac then moved to the Visual Studio project] (I manually created a file to make the code work):**
• Open Terminal and put
_xcrun --sdk iphoneos --show-sdk-path_

• If that works, you are good to go ahead and write
_mkdir ~/Desktop/onnxstub_
Or create a folder manually on your Desktop

_cd ~/Desktop/onnxstub_ (Go to the folder)

_SDK=$(xcrun --sdk iphoneos --show-sdk-path)_ (Create a variable to use so it won't build for mac as i first did and got another error in Visual Studio)

_clang -arch arm64 -isysroot $SDK -c stub_register_custom_ops.c -o stub_register_custom_ops.o_ (Create .o file)

libtool -static -o libregister_custom_ops_stub.a stub_register_custom_ops.o (Create .a file)

**Step 4 (I transferred and added the .a file to Visual Sudio project):**
• Use any way to bring the .a file to your Windows machine

• Place the .a file in Platforms/iOS/NativeStubs/ (or anywhere you want but make sure to change the path in next part)

• Add this snippet to the .csproj:
_<NativeReference Include="Platforms/iOS/NativeStubs/libregister_custom_ops_stub.a">
  <Kind>Static</Kind>
  <ForceLoad>true</ForceLoad>
</NativeReference>_

**Step 5 (The problem was persisting and this is what I did after, you might want to try if you get some of the problems):**

Problems:
- "Object not set to an instance of an object." (It sounds like a code problem but for me it was not)
- Again the error with _RegisterCustomOps appeared
- Some other errors that were crazy stuff

What I did:
• Delete bin and obj folders
• Restore Nuget Packages
• Clean Project
• Rebuild project
• Build on ios physical device using local device (this is to make sure the app builds and runs if the ONNX is not instantly used)
• Build over Remote Devices ([how to add a remote device](https://developer.apple.com/documentation/xcode/running-your-app-in-simulator-or-on-a-device#Connect-real-devices-to-your-Mac))

I guess you can also use a Simulator device but for me Simulator doesn't work.

After all the steps above my app started working. I hope this will help you all!

**Comment by kfrancis** [comment]
I'm sorry @snnn - this is complete? The set of numerous manual steps is actually how we should resolve this? This is blocking us.

<img width="1044" height="618" alt="Image" src="https://github.com/user-attachments/assets/cf7dbde3-6172-4c73-bc04-344db31acfec" />

**Comment by ben-dean** [comment]
The latest nugets are working fine. Builds and is functional.

**Comment by albyrock87** [comment]
I'm still getting a build error using `<PackageVersion Include="Microsoft.ML.OnnxRuntime" Version="1.23.1" />` & `<PackageReference Include="Microsoft.ML.OnnxRuntime" />`.

```
Finished external tool execution #21 in 00:00:00.3526139 and with exit code 1.
ld: warning: ignoring duplicate libraries: '-lSystem.Globalization.Native', '-lSystem.IO.Compression.Native', '-lSystem.Native', '-lSystem.Net.Security.Native', '-lSystem.Security.Cryptography.Native.Apple', '-lc++', '-lcompression', '-lmono-component-debugger', '-lmono-component-diagnostics_tracing', '-lmono-component-hot_reload', '-lmono-component-marshal-ilgen', '-lmonosgen-2.0', '-lxamarin-dotnet-debug'
ld: warning: object file (/Users/......my project pat here..../obj/Debug/net9.0-ios/iossimulator-arm64/onnxruntime.xcframework.zip/onnxruntime.xcframework/ios-arm64_x86_64-simulator/onnxruntime.framework/onnxruntime[arm64][2](prelinked_objects.o)) was built for newer 'iOS-simulator' version (15.1) than being linked (15.0)
1>Xamarin.Shared.Sdk.targets(1835,3): Error  : clang++ exited with code 1:
Undefined symbols for architecture arm64:
  "_RegisterCustomOps", referenced from:
      <initial-undefines>
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Edit: I solved the first warning by increasing the `<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">15.1</SupportedOSPlatformVersion>`
But I still get the error.

**Comment by albyrock87** [comment]
This issue has not been resolved.

**Comment by skottmckay** [comment]
> This issue has not been resolved.

Reference https://www.nuget.org/packages/Microsoft.ML.OnnxRuntime.Extensions.Dummy to resolve _RegisterCustomOps. The original issue was due to dotnet not expanding the xcframework as expected which should be resolved by https://github.com/microsoft/onnxruntime/issues/22661#issuecomment-2574372792.
