### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Exlsunshine** [Microsoft/onnxruntime#237]
**Describe the bug**
Build error.

**System information**
- OS Platform and Distribution 
Linux Ubuntu 16.04
- ONNX Runtime installed from 
source 
- ONNX Runtime version:
- Python 3:
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**To Reproduce**
```
./build.sh --config RelWithDebInfo --build_wheel
```

**Expected behavior**
Build successful.

**Screenshots**

2018-12-21 09:10:49,430 Build [DEBUG] - Defaulting to running update, build and test. 2018-12-21 09:10:49,431 Build [INFO] - Build started 2018-12-21 09:10:49,431 Build [DEBUG] - Running subprocess in '/home/exlsunshine/projects/onnxruntime' ['git', 'submodule', 'update', '--init', '--recursive'] 2018-12-21 09:10:49,638 Build [INFO] - Generating CMake build tree 2018-12-21 09:10:49,639 Build [DEBUG] - Running subprocess in '/home/exlsunshine/projects/onnxruntime/build/Linux/Debug' ['/usr/local/bin/cmake', '/home/exlsunshine/projects/onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDA_HOME=', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_JEMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=ON', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_USE_EIGEN_FOR_BLAS=ON', '-Donnxruntime_USE_OPENBLAS=OFF', '-Donnxruntime_USE_MKLDNN=OFF', '-Donnxruntime_USE_MKLML=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_BRAINSLICE=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-DCMAKE_BUILD_TYPE=Debug'] CMake Error at CMakeLists.txt:6 (onnxruntime_protobuf_generate): Unknown CMake command "onnxruntime_protobuf_generate". CMake Warning (dev) in CMakeLists.txt: No cmake_minimum_required command is present. A line of code such as cmake_minimum_required(VERSION 3.13) should be added at the top of the file. The version specified may be lower if you wish to support older CMake versions for this project. For more information run "cmake --help-policy CMP0000". This warning is for project developers. Use -Wno-dev to suppress it. -- Configuring incomplete, errors occurred! See also "/home/exlsunshine/projects/onnxruntime/cmake/CMakeFiles/CMakeOutput.log". Traceback (most recent call last): File "/home/exlsunshine/projects/onnxruntime/tools/ci_build/build.py", line 572, in <module> sys.exit(main()) File "/home/exlsunshine/projects/onnxruntime/tools/ci_build/build.py", line 545, in main args, cmake_extra_args) File "/home/exlsunshine/projects/onnxruntime/tools/ci_build/build.py", line 315, in generate_build_tree run_subprocess(cmake_args + ["-DCMAKE_BUILD_TYPE={}".format(config)], cwd=config_build_dir) File "/home/exlsunshine/projects/onnxruntime/tools/ci_build/build.py", line 143, in run_subprocess result = subprocess.run(args, cwd=cwd, check=True, env=my_env) File "/usr/lib/python3.6/subprocess.py", line 418, in run output=stdout, stderr=stderr) subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '/home/exlsunshine/projects/onnxruntime/cmake', '-Donnxruntime_RUN_ONNX_TESTS=OFF', '-Donnxruntime_GENERATE_TEST_REPORTS=ON', '-Donnxruntime_DEV_MODE=ON', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-Donnxruntime_USE_CUDA=OFF', '-Donnxruntime_CUDA_HOME=', '-Donnxruntime_CUDNN_HOME=', '-Donnxruntime_USE_JEMALLOC=OFF', '-Donnxruntime_ENABLE_PYTHON=ON', '-Donnxruntime_BUILD_CSHARP=OFF', '-Donnxruntime_BUILD_SHARED_LIB=OFF', '-Donnxruntime_USE_EIGEN_FOR_BLAS=ON', '-Donnxruntime_USE_OPENBLAS=OFF', '-Donnxruntime_USE_MKLDNN=OFF', '-Donnxruntime_USE_MKLML=OFF', '-Donnxruntime_USE_OPENMP=OFF', '-Donnxruntime_USE_TVM=OFF', '-Donnxruntime_USE_LLVM=OFF', '-Donnxruntime_ENABLE_MICROSOFT_INTERNAL=OFF', '-Donnxruntime_USE_BRAINSLICE=OFF', '-Donnxruntime_USE_NUPHAR=OFF', '-DCMAKE_BUILD_TYPE=Debug']' returned non-zero exit status 1.

**Comment by souptc** [comment]
what's your cmake version? onnxruntime require at least cmake 3.11

**Comment by Janamdeep** [comment]
I am also having the same problem. Can somebody help.
Cmake version is 3.12.4

**Comment by pranavsharma** [comment]
Something is possibly wrong with your cmake setup. May be the newer version of cmake is not in the path when you run build.sh. We don't see any problems in our CI pipelines.

**Comment by faxu** [comment]
@Janamdeep @Exlsunshine Can you guys provide more information to help debug if you are still experiencing this issue?

**Comment by Janamdeep** [comment]
@faxu @pranavsharma thank you very much. The issue is resolved now. I had to manually add the libraries in the CMakeLists.txt in the onnxruntime directory

**Comment by Timonsc** [comment]
Hi I still have the same problem. What libraries exactly, the ones that are listed in setup.py? And do you mean the CMakeLists.txt in .../onnxruntime/cmake ?

**Comment by Kammmil** [comment]
@Janamdeep 
can you tell me how to do it please? ;)
