### ISSUE TITLE
TreeEnsemble dies due to memory/segmentation errors with large membership values

### ISSUE THREAD

**Issue by meakbiyik** [microsoft/onnxruntime#25400]
### Describe the issue

I have been having issues with implementing XGBoost conversion with proper categorical feature support. Even with reasonably-sized models, is membership values is somewhat large (>50000), the runtime session does not even start, and get killed with kernel-level errors. In my modest 500 KB model with 80000 membership_values, I get:

`low swap: killing largest compressed process with pid 32049 (python3.12) and size 151948 MB`

Although I cannot share this model, I created below a simple example that can reproduce a `segmentation fault` for 40000 membership_values, based on the example in the documentation page: https://onnx.ai/onnx/operators/onnx_aionnxml_TreeEnsemble.html

Note that when I implement membership check using many EQ's and a TreeEnsembleRegressor, it works flawlessly until version 1.20.1, but crashes with the same error in 1.21.0.

### To reproduce

import numpy as np
import onnx
import onnxruntime as ort

node = onnx.helper.make_node(
    "TreeEnsemble",
    ["X"],
    ["Y"],
    domain="ai.onnx.ml",
    n_targets=4,
    aggregate_function=1,
    membership_values=onnx.helper.make_tensor(
        "membership_values",
        onnx.TensorProto.FLOAT,
        (40004,),
        [1.2, 3.7, 8, 9] * 10000 + [np.nan] + [12, 7] + [np.nan],
    ),
    nodes_missing_value_tracks_true=None,
    nodes_hitrates=None,
    post_transform=0,
    tree_roots=[0],
    nodes_modes=onnx.helper.make_tensor(
        "nodes_modes",
        onnx.TensorProto.UINT8,
        (3,),
        np.array([0, 6, 6], dtype=np.uint8),
    ),
    nodes_featureids=[0, 0, 0],
    nodes_splits=onnx.helper.make_tensor(
        "nodes_splits",
        onnx.TensorProto.FLOAT,
        (3,),
        np.array([11, 232344.0, np.nan], dtype=np.float32),
    ),
    nodes_trueleafs=[0, 1, 1],
    nodes_truenodeids=[1, 0, 1],
    nodes_falseleafs=[1, 0, 1],
    nodes_falsenodeids=[2, 2, 3],
    leaf_targetids=[0, 1, 2, 3],
    leaf_weights=onnx.helper.make_tensor(
        "leaf_weights", onnx.TensorProto.FLOAT, (4,), [1, 10, 1000, 100]
    ),
)
model = onnx.helper.make_model(
    onnx.helper.make_graph(
        [node],
        "test_model",
        [onnx.helper.make_tensor_value_info("X", onnx.TensorProto.FLOAT, [None, 4])],
        [onnx.helper.make_tensor_value_info("Y", onnx.TensorProto.FLOAT, [None, 4])],
    ),
    producer_name="onnx-example",
    ir_version=10,
    opset_imports=[onnx.helper.make_opsetid("ai.onnx.ml", 5)],
    domain="ai.onnx.ml",
)
providers = ['CPUExecutionProvider']
session = ort.InferenceSession(model.SerializeToString(), providers=providers)

### Urgency

Very urgent. I believe if we cannot resolve this in a couple weeks, we will have to stop using ONNX.

### Platform

Mac

### OS Version

Sonoma 14.7.2

### ONNX Runtime Installation

Released Package

### ONNX Runtime Version or Commit ID

1.22.0

### ONNX Runtime API

Python

### Architecture

ARM64

### Execution Provider

Default CPU

**Comment by xadupre** [comment]
Thanks for reporting this issue, I'll have a look tomorrow.

**Comment by xadupre** [comment]
One function is recursive and the recursivity depth is equal to the number of values in the set of values. The crash comes from a very long call stack.

**Comment by meakbiyik** [comment]
Thanks a lot for the quick investigation @xadupre. Do you have a estimate on when this can be resolved? I will need to force a temporary onnx runtime downgrade in our systems depending on the timeline.

**Comment by xadupre** [comment]
I'm working on it right now. I hope to submit a PR by the end of the day.

**Comment by xadupre** [comment]
In face there are two recursive functions. One to expand the membership rule into a succession of EQ, another one to fused of all of them back into a member ship rule. That's quite inefficient as it is now. I fixed one recursive function but I don't think that's the right way to go. I'll need another day.

**Comment by xadupre** [comment]
I looked into the implementation of TreeEnsemble and the MEMBER_SHIP implementation only supports integers so values like 1.2, 3.7 will prevent the chain of BRANCH_EQ to collapse. So I'm wondering what is the real scenario you want to address?

Having a membership rule based on pure float cannot be done easily. I suggest using a LabelEncoder to use int (https://onnx.ai/onnx/operators/onnx_aionnxml_LabelEncoder.html). How many distinct categories do you want to support? Based on your example, I assume many more than 32 and I fear that I have to rewrite many parts of the TreeEnsemble.

**Comment by meakbiyik** [comment]
> In face there are two recursive functions. One to expand the membership rule into a succession of EQ, another one to fused of all of them back into a member ship rule. That's quite inefficient as it is now. I fixed one recursive function but I don't think that's the right way to go. I'll need another day.

Yes, I noticed that too. I suspect it's for backward compatibility, but I think the first function can be skipped if the model is initialized as TreeEnsembleV5.

> I looked into the implementation of TreeEnsemble and the MEMBER_SHIP implementation only supports integers so values like 1.2, 3.7 will prevent the chain of BRANCH_EQ to collapse. So I'm wondering what is the real scenario you want to address?

Those values were just from the documentation's example; I normally use label-encoded integers in my own implementation.

> How many distinct categories do you want to support? Based on your example, I assume many more than 32 and I fear that I have to rewrite many parts of the TreeEnsemble.

Yes, unfortunately, this needs to scale to hundreds of thousands of values. For instance, a simple XGBoost model with one important categorical feature (100 cardinality) and 100 estimators can easily produce tens of thousands of membership values. XGBoost's partitioning logic, which occasionally creates very large categorical split nodes, exacerbates this problem.

If you've fixed the second loop (the membership check), couldn't we just skip the first loop that compacts nodes into BRANCH_MEMBER? I don't think the implementation would lose anything if that code were removed entirely.

**Comment by xadupre** [comment]
If you have many categories, I need to change the implementation of the MEMBER_SHIP rule in TreeEnsemble, using a bitset for example.

**Comment by meakbiyik** [comment]
That'd be awesome if it's feasible, but I could also do with the current way if it's too big of a hassle. I am otherwise considering to implement this as a NEQ tree, so any native implementation would be welcome.

**Comment by meakbiyik** [comment]
> That'd be awesome if it's feasible, but I could also do with the current way if it's too big of a hassle. I am otherwise considering to implement this as a NEQ tree, so any native implementation would be welcome.

Although admittedly a bit better performance would be appreciated 😄 I imagine bitmasks could be better in that regard?

**Comment by xadupre** [comment]
What is a NEQ tree? I did not look at the implementation of bitset, I assume it is efficient enough but I did not look how xgboost was doing this.

**Comment by meakbiyik** [comment]
I meant instead of using many EQ's that get folded into a MEMBER, many NEQ's that avoid that check and get processed without memory exploding 😄

I do not know how xgboost processes it internally as well, just that the nodes look like lists when visualized as JSON.

In any case, I welcome any implementation you see fit. IMO one can even scrape all the Member-to-EQ & EQ-to-Member conversions and only process the members properly, potentially with a bitmask.

**Comment by xadupre** [comment]
I should be able to come up with something on Friday with bitset. We can do something better later.

**Comment by meakbiyik** [comment]
Thanks, looking forward to it! If we can merge both this and #25410, then TreeEnsemble will be consistent with XGBoost quite soon :)

**Comment by xadupre** [comment]
It seems xgboost is using this: https://github.com/dmlc/xgboost/blob/master/src/common/bitfield.h.

**Comment by meakbiyik** [comment]
Hmm looks efficient. Also good to support 0-indexed categories.

**Comment by xadupre** [comment]
I finished my PR. I used unorderst_set (bitset needs to know the number of bits to use in advance). We can optimize the code later. I left the existing code if the set of categories can be masked and introduced a new node rule (BRANCH_MEMBER_BIGSET). It is working fine on the example in this issue. I let you confirm that fits your needs.

**Comment by meakbiyik** [comment]
Fantastic, will give it a try over the weekend 👌Out of curiosity, why is the number of bits not known in advance? Is this to avoid the overhead of a length check every time?

**Comment by meakbiyik** [comment]
@xadupre I am unable to test this as I cannot build the wheel of onnxruntime via pip, getting [this error](http://github.com/microsoft/onnxruntime/issues/24570). However, if the tests run, missing cases etc. are properly handled, and that we are avoiding both recursive functions, it should work out fine.

**Comment by xadupre** [comment]
Fixed.

**Comment by meakbiyik** [comment]
@xadupre I wanted to test this locally after awhile, and installed the nightly build of onnxruntime `1.23.0.dev20250517001` but I still can reproduce the original issue:

```python
import numpy as np
import onnx
import onnxruntime as ort

print(ort.__version__)

node = onnx.helper.make_node(
    "TreeEnsemble",
    ["X"],
    ["Y"],
    domain="ai.onnx.ml",
    n_targets=4,
    aggregate_function=1,
    membership_values=onnx.helper.make_tensor(
        "membership_values",
        onnx.TensorProto.FLOAT,
        (40004,),
        [1.2, 3.7, 8, 9] * 10000 + [np.nan] + [12, 7] + [np.nan],
    ),
    nodes_missing_value_tracks_true=None,
    nodes_hitrates=None,
    post_transform=0,
    tree_roots=[0],
    nodes_modes=onnx.helper.make_tensor(
        "nodes_modes",
        onnx.TensorProto.UINT8,
        (3,),
        np.array([0, 6, 6], dtype=np.uint8),
    ),
    nodes_featureids=[0, 0, 0],
    nodes_splits=onnx.helper.make_tensor(
        "nodes_splits",
        onnx.TensorProto.FLOAT,
        (3,),
        np.array([11, 232344.0, np.nan], dtype=np.float32),
    ),
    nodes_trueleafs=[0, 1, 1],
    nodes_truenodeids=[1, 0, 1],
    nodes_falseleafs=[1, 0, 1],
    nodes_falsenodeids=[2, 2, 3],
    leaf_targetids=[0, 1, 2, 3],
    leaf_weights=onnx.helper.make_tensor(
        "leaf_weights", onnx.TensorProto.FLOAT, (4,), [1, 10, 1000, 100]
    ),
)
model = onnx.helper.make_model(
    onnx.helper.make_graph(
        [node],
        "test_model",
        [onnx.helper.make_tensor_value_info("X", onnx.TensorProto.FLOAT, [None, 4])],
        [onnx.helper.make_tensor_value_info("Y", onnx.TensorProto.FLOAT, [None, 4])],
    ),
    producer_name="onnx-example",
    ir_version=10,
    opset_imports=[onnx.helper.make_opsetid("ai.onnx.ml", 5)],
    domain="ai.onnx.ml",
)
providers = ['CPUExecutionProvider']
session = ort.InferenceSession(model.SerializeToString(), providers=providers)
```

outputs

```
1.23.0.dev20250517001
zsh: segmentation fault
```

Do you know if the nightly build includes your fix? How can I validate it?

**Comment by meakbiyik** [comment]
@xadupre should I create a new issue, or should we reopen this one in case the bug is still there (I do not have the permissions for it)? otherwise I also would welcome any insights on the onnxruntime release/build system 😄

**Comment by meakbiyik** [comment]
Scratch this, my bad. It seems there hasn't been any MacOS nightly for the last months, so the windows nightly works. Thanks again!
