### ISSUE TITLE
[Build] error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce'

### ISSUE THREAD

**Issue by aborrero** [microsoft/onnxruntime#26229]
### Describe the issue

I see the following build errors with onnxruntime v1.23.0:

```
WARN 🔗 In file included from /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3:
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc: In function 'void onnxruntime::contrib::RegisterContribSchemas()':
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:50:18: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗    50 |       schema_func(ONNX_NAMESPACE::OpSchema(#name, __FILE__, __LINE__))
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:46:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE'
WARN 🔗    46 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE(Counter, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:44:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE'
WARN 🔗    44 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE(__COUNTER__, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:2853:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE'
WARN 🔗  2853 |   ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE(AttnLSTM, RegisterAttnLSTMContribOpSchema);
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:50:18: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗    50 |       schema_func(ONNX_NAMESPACE::OpSchema(#name, __FILE__, __LINE__))
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:46:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE'
WARN 🔗    46 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE(Counter, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:44:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE'
WARN 🔗    44 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE(__COUNTER__, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:2854:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE'
WARN 🔗  2854 |   ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE(Range, RegisterRangeOpSchema);
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:2927:46: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  2927 |       .SetContextDependentFunctionBodyBuilder(
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3035:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3035 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3090:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3090 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3153:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3153 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3200:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3200 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3245:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3245 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3307:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3307 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3385:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3385 |       .TypeConstraint(
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3446:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3446 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3510:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3510 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3587:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3587 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3641:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3641 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3811:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3811 |       .TypeAndShapeInferenceFunction([](InferenceContext& ctx) {
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/logging/sinks/ostream_sink.cc.o
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/config_options.cc.o
WARN 🔗 make[2]: *** [CMakeFiles/onnxruntime_graph.dir/build.make:121: CMakeFiles/onnxruntime_graph.dir/home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc.o] Error 1
INFO 🔗 [ 13%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SgemmKernelM1TransposeBAvx.S.o
INFO 🔗 [ 13%] Running cpp protocol buffer compiler (lite) on /home/build/onnxruntime/test/proto/tml.proto
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnx_test_data_proto.dir/tml.pb.cc.o
WARN 🔗 make[1]: *** [CMakeFiles/Makefile2:906: CMakeFiles/onnxruntime_session.dir/all] Error 2
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/file_util.cc.o
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/bias_softmax_fusion.cc.o
INFO 🔗 [ 39%] Linking CXX static library libonnxruntime_optimizer.a
WARN 🔗 make[1]: *** [CMakeFiles/Makefile2:673: CMakeFiles/onnxruntime_graph.dir/all] Error 2
WARN 🔗 make[1]: *** Waiting for unfinished jobs....
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/profiler.cc.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SgemmTransposePackB16x4Avx.S.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/copy.cc.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/cast_chain_elimination.cc.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SconvKernelAvx.S.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/scoped_env_vars.cc.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SpoolKernelAvx.S.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SoftmaxKernelAvx.S.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/intrinsics/avx/min_max_elements.cpp.o
WARN 🔗 make[1]: *** [CMakeFiles/Makefile2:673: CMakeFiles/onnxruntime_graph.dir/all] Error 2
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/profiler_common.cc.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/cast_elimination.cc.o
INFO 🔗 [ 39%] Built target onnxruntime_optimizer
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/customregistry.cc.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/temp_dir.cc.o
INFO 🔗 [ 15%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/semver.cc.o
INFO 🔗 [ 15%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/tensors_from_file.cc.o
INFO 🔗 [ 15%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/QgemmU8S8KernelAvx2.S.o
INFO 🔗 [ 16%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/common_subexpression_elimination.cc.o
WARN 🔗 In file included from /home/build/onnxruntime/core/common/semver.cc:4:
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:18:3: error: 'uint32_t' does not name a type
WARN 🔗    18 |   uint32_t major{};
WARN 🔗       |   ^~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:10:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
WARN 🔗     9 | #include "core/common/status.h"
WARN 🔗   +++ |+#include <cstdint>
WARN 🔗    10 | 
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:19:3: error: 'uint32_t' does not name a type
WARN 🔗    19 |   uint32_t minor{};
WARN 🔗       |   ^~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:19:3: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:20:3: error: 'uint32_t' does not name a type
WARN 🔗    20 |   uint32_t patch{};
WARN 🔗       |   ^~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:20:3: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
INFO 🔗 [ 16%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/data_transfer.cc.o
INFO 🔗 [ 17%] Building CXX object _deps/onnx-build/CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
INFO 🔗 [ 17%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/QgemvU8S8KernelAvx2.S.o
INFO 🔗 [ 17%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/QgemmU8U8KernelAvx2.S.o
WARN 🔗 In file included from /home/build/onnxruntime/core/common/semver.cc:8:
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc: In function 'onnxruntime::common::Status onnxruntime::ParseSemVerVersion(std::string_view, SemVerVersion*)':
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:41:79: error: 'struct onnxruntime::SemVerVersion' has no member named 'major'
WARN 🔗    41 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[1], semver_version.major));
WARN 🔗       |                                                                               ^~~~~
WARN 🔗 /home/build/include/onnxruntime/core/common/common.h:255:21: note: in definition of macro 'ORT_RETURN_IF_ERROR_SESSIONID'
WARN 🔗   255 |     auto _status = (expr);                                                                                             \
WARN 🔗       |                     ^~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:41:3: note: in expansion of macro 'ORT_RETURN_IF_ERROR'
WARN 🔗    41 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[1], semver_version.major));
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:42:79: error: 'struct onnxruntime::SemVerVersion' has no member named 'minor'
WARN 🔗    42 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[2], semver_version.minor));
WARN 🔗       |                                                                               ^~~~~
WARN 🔗 /home/build/include/onnxruntime/core/common/common.h:255:21: note: in definition of macro 'ORT_RETURN_IF_ERROR_SESSIONID'
WARN 🔗   255 |     auto _status = (expr);                                                                                             \
WARN 🔗       |                     ^~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:42:3: note: in expansion of macro 'ORT_RETURN_IF_ERROR'
WARN 🔗    42 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[2], semver_version.minor));
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:43:79: error: 'struct onnxruntime::SemVerVersion' has no member named 'patch'
WARN 🔗    43 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[3], semver_version.patch));
WARN 🔗       |                                                                               ^~~~~
WARN 🔗 /home/build/include/onnxruntime/core/common/common.h:255:21: note: in definition of macro 'ORT_RETURN_IF_ERROR_SESSIONID'
WARN 🔗   255 |     auto _status = (expr);                                                                                             \
WARN 🔗       |                     ^~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:43:3: note: in expansion of macro 'ORT_RETURN_IF_ERROR'
WARN 🔗    43 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[3], semver_version.patch));
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~
```

I'm building the package like this:

```
./build.sh --config RelWithDebInfo --build_shared_lib --parallel --enable_training_apis --allow_running_as_root --cmake_extra_defines FETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER
```

I'm building directly from https://github.com/microsoft/onnxruntime.git commit be835efc56aca19b8e810538ec93c8e150e0fc61 and recursing git submodule checkout.

Is this somehow related to this other PR? https://github.com/microsoft/onnxruntime/pull/24449

Please advice on how to proceed.

### Target platform

x86_64

### Build script

./build.sh --config RelWithDebInfo --build_shared_lib --parallel --enable_training_apis --allow_running_as_root --cmake_extra_defines FETCHCONTENT_TRY_FIND_PACKAGE_MODE=NEVER

### Error / output

WARN 🔗 In file included from /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3:
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc: In function 'void onnxruntime::contrib::RegisterContribSchemas()':
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:50:18: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗    50 |       schema_func(ONNX_NAMESPACE::OpSchema(#name, __FILE__, __LINE__))
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:46:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE'
WARN 🔗    46 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE(Counter, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:44:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE'
WARN 🔗    44 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE(__COUNTER__, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:2853:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE'
WARN 🔗  2853 |   ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE(AttnLSTM, RegisterAttnLSTMContribOpSchema);
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:50:18: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗    50 |       schema_func(ONNX_NAMESPACE::OpSchema(#name, __FILE__, __LINE__))
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:46:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE'
WARN 🔗    46 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_ELSEWHERE(Counter, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.h:44:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE'
WARN 🔗    44 |   ONNX_CONTRIB_OPERATOR_SCHEMA_UNIQ_HELPER_ELSEWHERE(__COUNTER__, name, schema_func)
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:2854:3: note: in expansion of macro 'ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE'
WARN 🔗  2854 |   ONNX_CONTRIB_OPERATOR_SCHEMA_ELSEWHERE(Range, RegisterRangeOpSchema);
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:2927:46: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  2927 |       .SetContextDependentFunctionBodyBuilder(
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3035:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3035 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3090:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3090 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3153:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3153 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3200:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3200 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3245:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3245 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3307:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3307 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3385:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3385 |       .TypeConstraint(
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3446:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3446 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3510:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3510 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3587:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3587 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3641:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3641 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
WARN 🔗 /home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc:3811:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
WARN 🔗  3811 |       .TypeAndShapeInferenceFunction([](InferenceContext& ctx) {
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/logging/sinks/ostream_sink.cc.o
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/config_options.cc.o
WARN 🔗 make[2]: *** [CMakeFiles/onnxruntime_graph.dir/build.make:121: CMakeFiles/onnxruntime_graph.dir/home/build/onnxruntime/core/graph/contrib_ops/contrib_defs.cc.o] Error 1
INFO 🔗 [ 13%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SgemmKernelM1TransposeBAvx.S.o
INFO 🔗 [ 13%] Running cpp protocol buffer compiler (lite) on /home/build/onnxruntime/test/proto/tml.proto
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnx_test_data_proto.dir/tml.pb.cc.o
WARN 🔗 make[1]: *** [CMakeFiles/Makefile2:906: CMakeFiles/onnxruntime_session.dir/all] Error 2
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/file_util.cc.o
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/bias_softmax_fusion.cc.o
INFO 🔗 [ 39%] Linking CXX static library libonnxruntime_optimizer.a
WARN 🔗 make[1]: *** [CMakeFiles/Makefile2:673: CMakeFiles/onnxruntime_graph.dir/all] Error 2
WARN 🔗 make[1]: *** Waiting for unfinished jobs....
INFO 🔗 [ 13%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/profiler.cc.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SgemmTransposePackB16x4Avx.S.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/copy.cc.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/cast_chain_elimination.cc.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SconvKernelAvx.S.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/scoped_env_vars.cc.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SpoolKernelAvx.S.o
INFO 🔗 [ 14%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/SoftmaxKernelAvx.S.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/intrinsics/avx/min_max_elements.cpp.o
WARN 🔗 make[1]: *** [CMakeFiles/Makefile2:673: CMakeFiles/onnxruntime_graph.dir/all] Error 2
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/profiler_common.cc.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/cast_elimination.cc.o
INFO 🔗 [ 39%] Built target onnxruntime_optimizer
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/customregistry.cc.o
INFO 🔗 [ 14%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/temp_dir.cc.o
INFO 🔗 [ 15%] Building CXX object CMakeFiles/onnxruntime_common.dir/home/build/onnxruntime/core/common/semver.cc.o
INFO 🔗 [ 15%] Building CXX object CMakeFiles/onnxruntime_test_utils.dir/home/build/onnxruntime/test/util/tensors_from_file.cc.o
INFO 🔗 [ 15%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/QgemmU8S8KernelAvx2.S.o
INFO 🔗 [ 16%] Building CXX object CMakeFiles/onnxruntime_optimizer.dir/home/build/onnxruntime/core/optimizer/common_subexpression_elimination.cc.o
WARN 🔗 In file included from /home/build/onnxruntime/core/common/semver.cc:4:
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:18:3: error: 'uint32_t' does not name a type
WARN 🔗    18 |   uint32_t major{};
WARN 🔗       |   ^~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:10:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
WARN 🔗     9 | #include "core/common/status.h"
WARN 🔗   +++ |+#include <cstdint>
WARN 🔗    10 | 
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:19:3: error: 'uint32_t' does not name a type
WARN 🔗    19 |   uint32_t minor{};
WARN 🔗       |   ^~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:19:3: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:20:3: error: 'uint32_t' does not name a type
WARN 🔗    20 |   uint32_t patch{};
WARN 🔗       |   ^~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.h:20:3: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
INFO 🔗 [ 16%] Building CXX object CMakeFiles/onnxruntime_framework.dir/home/build/onnxruntime/core/framework/data_transfer.cc.o
INFO 🔗 [ 17%] Building CXX object _deps/onnx-build/CMakeFiles/onnx.dir/onnx/defs/quantization/defs.cc.o
INFO 🔗 [ 17%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/QgemvU8S8KernelAvx2.S.o
INFO 🔗 [ 17%] Building ASM object CMakeFiles/onnxruntime_mlas.dir/home/build/onnxruntime/core/mlas/lib/x86_64/QgemmU8U8KernelAvx2.S.o
WARN 🔗 In file included from /home/build/onnxruntime/core/common/semver.cc:8:
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc: In function 'onnxruntime::common::Status onnxruntime::ParseSemVerVersion(std::string_view, SemVerVersion*)':
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:41:79: error: 'struct onnxruntime::SemVerVersion' has no member named 'major'
WARN 🔗    41 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[1], semver_version.major));
WARN 🔗       |                                                                               ^~~~~
WARN 🔗 /home/build/include/onnxruntime/core/common/common.h:255:21: note: in definition of macro 'ORT_RETURN_IF_ERROR_SESSIONID'
WARN 🔗   255 |     auto _status = (expr);                                                                                             \
WARN 🔗       |                     ^~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:41:3: note: in expansion of macro 'ORT_RETURN_IF_ERROR'
WARN 🔗    41 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[1], semver_version.major));
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:42:79: error: 'struct onnxruntime::SemVerVersion' has no member named 'minor'
WARN 🔗    42 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[2], semver_version.minor));
WARN 🔗       |                                                                               ^~~~~
WARN 🔗 /home/build/include/onnxruntime/core/common/common.h:255:21: note: in definition of macro 'ORT_RETURN_IF_ERROR_SESSIONID'
WARN 🔗   255 |     auto _status = (expr);                                                                                             \
WARN 🔗       |                     ^~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:42:3: note: in expansion of macro 'ORT_RETURN_IF_ERROR'
WARN 🔗    42 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[2], semver_version.minor));
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:43:79: error: 'struct onnxruntime::SemVerVersion' has no member named 'patch'
WARN 🔗    43 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[3], semver_version.patch));
WARN 🔗       |                                                                               ^~~~~
WARN 🔗 /home/build/include/onnxruntime/core/common/common.h:255:21: note: in definition of macro 'ORT_RETURN_IF_ERROR_SESSIONID'
WARN 🔗   255 |     auto _status = (expr);                                                                                             \
WARN 🔗       |                     ^~~~
WARN 🔗 /home/build/onnxruntime/core/common/semver.cc:43:3: note: in expansion of macro 'ORT_RETURN_IF_ERROR'
WARN 🔗    43 |   ORT_RETURN_IF_ERROR(parse_version_component(match_result[3], semver_version.patch));
WARN 🔗       |   ^~~~~~~~~~~~~~~~~~~

**Comment by eKevinHoang** [comment]
If you want to build onnxruntime 1.23.0 or 1.23.1 with the latest ONNX 1.19.1, you’ll need to modify the source code for it to run properly.

However, if you only need to build it, you just need to remove any existing ONNX library installed on your system, then build it following the instructions in this document: https://onnxruntime.ai/docs/build/.
onnxruntime will automatically download and build the required libraries from the deps.txt file.

Hope this helps you!

**Comment by GaetanLepage** [comment]
We are facing the same issue when trying to bump `onnxruntime` from `1.22.2` to `1.23.1` in nixpkgs (https://github.com/NixOS/nixpkgs/pull/450587).

We are injecting the `1.18.0` source files of `onnx`, [as mentionned in `cmake/deps.txt`](https://github.com/microsoft/onnxruntime/blob/v1.23.1/cmake/deps.txt#L37). The CMake logs confirm that the `ONNX version` is indeed `1.18.0`:
```
...
--
-- ******** Summary ********
--   CMake version                     : 4.1.1
--   CMake command                     : /nix/store/2lrbixyw95bjg0x1aav648r0h0zsj2jl-cmake-4.1.1/bin/cmake
--   System                            : Linux
--   C++ compiler                      : /nix/store/dmypp1h4ldn0vfk3fi6yfyf5yxp9yz0k-gcc-wrapper-14.3.0/bin/g++
--   C++ compiler version              : 14.3.0
--   CXX flags                         :  -ffunction-sections -fdata-sections -DCPUINFO_SUPPORTED -Wnon-virtual-dtor
--   Build type                        : Release
--   Compile definitions               : EIGEN_MPL2_ONLY;_GNU_SOURCE
--   CMAKE_PREFIX_PATH                 :
--   CMAKE_INSTALL_PREFIX              : /nix/store/2nzghr6sk9qk66byips3lf1y8hls8az0-onnxruntime-1.23.1
--   CMAKE_MODULE_PATH                 : /build/source/cmake/external
--
--   ONNX version                      : 1.18.0
--   ONNX NAMESPACE                    : onnx
--   ONNX_USE_LITE_PROTO               : ON
--   USE_PROTOBUF_SHARED_LIBS          : OFF
--   ONNX_DISABLE_EXCEPTIONS           : OFF
--   ONNX_DISABLE_STATIC_REGISTRATION  : OFF
--   ONNX_WERROR                       : OFF
--   ONNX_BUILD_TESTS                  : OFF
--   BUILD_SHARED_LIBS                 : OFF
--
--   Protobuf compiler                 : /nix/store/59ywwk7f1saqgfynzj4sij1ksnmi214r-protobuf-32.1/bin/protoc
--   Protobuf includes                 :
--   Protobuf libraries                :
--   ONNX_BUILD_PYTHON                 : OFF
...
```

However, the build still fails with:
```
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc: In function 'void onnxruntime::contrib::RegisterCollectiveOps()':
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:26:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
   26 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:47:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
   47 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:79:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
   79 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:155:37: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  155 |       .TypeAndShapeInferenceFunction([](ONNX_NAMESPACE::InferenceContext& ctx) {
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:186:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  186 |       .TypeConstraint(
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:269:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  269 |       .TypeConstraint("Tind", {"tensor(int32)", "tensor(int64)"}, "Constrain indices to integer types");
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:314:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  314 |       .TypeConstraint("T", OpSchema::all_tensor_types_ir4(), "Constrain input and output types to all tensor types.");
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:351:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  351 |       .TypeConstraint("T", OpSchema::all_tensor_types_ir4(), "Constrain input and output types to all tensors.");
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:392:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  392 |       .TypeConstraint("T", OpSchema::all_tensor_types_ir4(), "Constrain input and output types to all tensors.");
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:433:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  433 |       .TypeConstraint("T", OpSchema::all_tensor_types_ir4(), "Constrain input and output types to all tensors.");
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:474:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  474 |       .TypeConstraint("T", OpSchema::all_tensor_types_ir4(), "Constrain input and output types to all tensors.");
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:511:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  511 |       .TypeConstraint("T", OpSchema::all_tensor_types_ir4(), "Constrain input and output types to all tensors.");
/build/source/onnxruntime/core/graph/contrib_ops/collective_defs.cc:548:22: error: conversion from 'onnx::OpSchema' to non-scalar type 'onnx::OpSchemaRegistry::OpSchemaRegisterOnce' requested
  548 |       .TypeConstraint("T", OpSchema::all_tensor_types_ir4(), "Constrain input and output types to all tensors.");
```

Anything I missed?

**Comment by Harry-Chen** [comment]
I got the same error as @GaetanLepage when compiling onnxruntime 1.23.1 with either onnx 1.18.0 or onnx 1.19.1. This also blocks the update of packages in Debian.

**Comment by GaetanLepage** [comment]
> Applying stale label due to no activity in 30 days

Still relevant.

**Comment by GaetanLepage** [comment]
Still relevant.

**Comment by GaetanLepage** [comment]
In the end, we managed to build `onnxruntime` 1.23.2 in nixpkgs.

https://github.com/NixOS/nixpkgs/pull/450587

**Comment by justinchuby** [comment]
Fixed

**Comment by WilliamTambellini** [comment]
The onnx part has been likely fixed (tks @cyyever) in
https://github.com/onnx/onnx/commit/595a069aaac07586f111681245bc808ee63551f8
onnxrt 1.23.x still seems to point to onnx1.18.0 and still fails to compile though:
```
~/repos/onnxruntime ((HEAD detached at origin/rel-1.23.4)) $ cat cmake/deps.txt | grep 'onnx;'
onnx;https://github.com/onnx/onnx/archive/refs/tags/v1.18.0.zip;f156d032a3af91b66d554e11158b33ca77bbb1f2

~/repos/onnxruntime ((HEAD detached at origin/rel-1.23.5)) $ cat cmake/deps.txt | grep 'onnx;'
onnx;https://github.com/onnx/onnx/archive/refs/tags/v1.18.0.zip;f156d032a3af91b66d554e11158b33ca77bbb1f2
```
onnxrt 1.24 upgraded to onnx 1.20 and builds correctly:
```
~/repos/onnxruntime ((HEAD detached at origin/rel-1.24.6)) $ cat cmake/deps.txt | grep 'onnx;'
onnx;https://github.com/onnx/onnx/archive/refs/tags/v1.20.1.zip;30b80c81a1a381188896e86abe460c3c3f3091fd
```
