### ISSUE TITLE
Java runtime with GraalVM build

### ISSUE THREAD

**Issue by OmriShiv** [microsoft/onnxruntime#5172]
Hello,
I'm trying to use the runtime with a container image built from Quarkus native build. I'm facing a linking issue, but I cannot seem to figure out why. Running the build locally on my machine works fine, running the build in a container without being compiled works fine, however, running it in the native container doesn't work. Failing on 

```
Caused by: java.lang.UnsatisfiedLinkError: ai.onnxruntime.OrtEnvironment.createHandle(JILjava/lang/String;)J [symbol: Java_ai_onnxruntime_OrtEnvironment_createHandle or Java_ai_onnxruntime_OrtEnvironment_createHandle__JILjava_lang_String_2]
	at com.oracle.svm.jni.access.JNINativeLinkage.getOrFindEntryPoint(JNINativeLinkage.java:145)
	at com.oracle.svm.jni.JNIGeneratedMethodSupport.nativeCallAddress(JNIGeneratedMethodSupport.java:57)
	at ai.onnxruntime.OrtEnvironment.createHandle(OrtEnvironment.java)
	at ai.onnxruntime.OrtEnvironment.<init>(OrtEnvironment.java:122)
	at ai.onnxruntime.OrtEnvironment.getEnvironment(OrtEnvironment.java:83)
	at ai.onnxruntime.OrtEnvironment.getEnvironment(OrtEnvironment.java:45)
```

I have tried putting the libraries on the image manually and starting the application with:
`./application -Donnxruntime.native.onnxruntime.path=/work/library/libonnxruntime.so -Donnxruntime.native.onnxruntime4j_jni.path=/work/library/libonnxruntime4j_jni.so`
but it still fails the same way. 

I have also tried to include them in the `resources-config.json` and add that to the Graal build parameter, but it is still failing.

Any help would be appreciated

**Comment by Craigacp** [comment]
Could you say a little more about how you executed native-image (e.g. command line parameters, if you profiled the application first etc)?

**Comment by OmriShiv** [comment]
Absolutely (let me preface by saying this is my first time using Quarkus or native images in general):

I added the following to `application.properties`:
```
quarkus.native.additional-build-args =\
-H:ResourceConfigurationFiles=resources-config.json, \
-H:ReflectionConfigurationFiles=reflection-config.json
```
Which contain:
```
{
  "resources": [
    {"pattern":"\\Qai/onnxruntime/native/linux-x64/libonnxruntime.so\\E"},
    {"pattern":"\\Qai/onnxruntime/native/linux-x64/libonnxruntime4j_jni.so\\E"}
  ]
}
```

and
```
[
  {
    "name" : "ai.onnxruntime.OrtEnvironment",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```

I also added libgomp to the Dockerfile
```
RUN microdnf -y install libgomp \
    && microdnf update \
    && microdnf clean all
```

On the command line, I use
```
./gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true && \
 docker build -f src/main/docker/Dockerfile.native -t quarkus/test-service .
```

I've tried adding the libraries onto the image, I've tried starting the application with 
```
./application -Donnxruntime.native.onnxruntime.path=/usr/lib64/libonnxruntime.so -Donnxruntime.native.onnxruntime4j_jni.path=/usr/lib64/libonnxruntime4j_jni.so
```
I've tried skipping and not skipping the loading of the library. Not sure what the right combination is.

**Comment by Craigacp** [comment]
Using graalvm 20.2 based on Java 8 on macOS 10.15 I've managed to successfully build a native image the following way:

```shell
/path/to/graal/java -agentlib:native-image-agent=config-output-dir=META-INF -cp .:onnxruntime-1.4.0.jar sample.ScoreMNIST cnn_mnist_pytorch.onnx mnist.t
/path/to/graal/native-image -H:+JNI -H:+ReportExceptionStackTraces -H:+StackTrace -H:ConfigurationFileDirectories=META-INF --no-server --no-fallback -cp .:onnxruntime-1.4.0.jar sample.ScoreMNIST
```

Had a few false starts which I'm not so sure about (I had to run the java agent a couple of times to get all the JNI codepaths, and there were some other issues), but I ended up with a roughly 35 MB binary which can score both the cnn and logistic regression test models in the java folder.

Unfortunately I don't know anything about Quarkus and it's build process, so after you've checked you're on the latest Graal it might be worth talking to them about how to get the command line parameters for native image in the right place.

This is the jni-config.json file generated from the agent:
```json

[
{
  "name":"ai.onnxruntime.MapInfo",
  "methods":[{"name":"<init>","parameterTypes":["int","ai.onnxruntime.OnnxJavaType","ai.onnxruntime.OnnxJavaType"] }]
},
{
  "name":"ai.onnxruntime.NodeInfo",
  "methods":[{"name":"<init>","parameterTypes":["java.lang.String","ai.onnxruntime.ValueInfo"] }]
},
{
  "name":"ai.onnxruntime.NodeInfo[]"
},
{
  "name":"ai.onnxruntime.OnnxJavaType",
  "methods":[{"name":"mapFromOnnxTensorType","parameterTypes":["ai.onnxruntime.TensorInfo$OnnxTensorType"] }]
},
{
  "name":"ai.onnxruntime.OnnxSequence",
  "methods":[{"name":"<init>","parameterTypes":["long","long","ai.onnxruntime.SequenceInfo"] }]
},
{
  "name":"ai.onnxruntime.OnnxTensor",
  "methods":[{"name":"<init>","parameterTypes":["long","long","ai.onnxruntime.TensorInfo"] }]
},
{
  "name":"ai.onnxruntime.OnnxValue"
},
{
  "name":"ai.onnxruntime.OnnxValue[]"
},
{
  "name":"ai.onnxruntime.SequenceInfo",
  "methods":[{"name":"<init>","parameterTypes":["int","ai.onnxruntime.MapInfo"] }]
},
{
  "name":"ai.onnxruntime.TensorInfo",
  "methods":[{"name":"<init>","parameterTypes":["long[]","ai.onnxruntime.OnnxJavaType","ai.onnxruntime.TensorInfo$OnnxTensorType"] }]
},
{
  "name":"ai.onnxruntime.TensorInfo$OnnxTensorType",
  "methods":[{"name":"mapFromInt","parameterTypes":["int"] }]
},
{
  "name":"java.lang.ClassLoader",
  "methods":[{"name":"loadClass","parameterTypes":["java.lang.String"] }]
},
{
  "name":"java.lang.ClassNotFoundException"
},
{
  "name":"java.lang.String"
},
{
  "name":"java.lang.String[]"
}
]
```
The reflect config didn't have anything onnx related in it, and the resource-config.json was this:
```json
{
  "resources":[
    {"pattern":"\\QMETA-INF/services/jdk.vm.ci.hotspot.HotSpotJVMCIBackendFactory\\E"}, 
    {"pattern":"\\QMETA-INF/services/jdk.vm.ci.services.JVMCIServiceLocator\\E"}, 
    {"pattern":"\\Qai/onnxruntime/native/osx-x64/libonnxruntime.dylib\\E"}, 
    {"pattern":"\\Qai/onnxruntime/native/osx-x64/libonnxruntime4j_jni.dylib\\E"}
  ],
  "bundles":[]
}
```

**Comment by OmriShiv** [comment]
This is great, thank you so much! Let me check it locally and see if I can fix it on Quarkus

**Comment by OmriShiv** [comment]
@Craigacp I finally got around to trying to replicate your example and that works on my local machine. Have you been able to try and create a new Java project with ONNX as a dependency and have that work with native builds? I am still seeing the same issues when building my project using my local graal environment, not using the quarkus wrapper

**Comment by Craigacp** [comment]
I've not tried it in another project, but I'd be surprised if it didn't work given the modular nature of it. Does your jni-config.json look like it's got the right bits in? And is the agent still being run to generate all the config files?

**Comment by OmriShiv** [comment]
I just tried to do this with a very basic project that depends on the runtime and it works, so it must be something with how Quarkus does the packaging. Thank you for helping me track this down!

**Comment by neomatrix369** [comment]
@OmriShiv I see this issue is resolved. I have some experience with building native-images from jars including those that have external linking that can be tricky. And I put together this [shell-script to build native image from jar files](https://github.com/neomatrix369/awesome-ai-ml-dl/blob/master/examples/tribuo/builder.sh), also see the usage illustrations in the [README](https://github.com/neomatrix369/awesome-ai-ml-dl/tree/master/examples/tribuo#native-image-build-optional). In case you are trying to build artifacts outside the Quarkus world this might help.

**Comment by OmriShiv** [comment]
@neomatrix369 Thank you. I actually did manage to get this to work outside of Quarkus; but have still not been able to get it to work with Quarkus https://github.com/quarkusio/quarkus/issues/12469.

**Comment by geichelberger** [comment]
I stumbled across the same error; adding the two additional build args and an appropriate `jni-config.json` and `resources-config.json` similar to the example above was sufficient.

```
    additional-build-args:
      - "--initialize-at-run-time=ai.onnxruntime.OrtEnvironment"
      - "--initialize-at-run-time=ai.onnxruntime.OnnxRuntime"
```

If I interpret the stack trace correctly, it tries to find a `createHandle` function with one argument (java.lang.String), but the function has at least three arguments.

**Comment by Craigacp** [comment]
GraalVM native-image now includes ONNX Runtime as it runs the ML models used in the profile guided optimization, which I think is why you need to reinit the environment at runtime.

**Comment by geichelberger** [comment]
The included ONNX Runtime causes another Problem: https://github.com/oracle/graal/issues/8431, but it worked with the version bundled with the Quarkus tooling.
