### ISSUE TITLE
DirectML Runtime error in GPT-2-LM-HEAD model with variable sized input.

### ISSUE THREAD

**Issue by hendrik-skubch** [microsoft/onnxruntime#6075]
**Describe the bug**
When performing inference with GPT-2-LM-Head (https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2), DirectML execution provider fails if the input is not of size 8 with the message:
```
2020-12-08 14:07:36.3271185 [I:onnxruntime:, sequential_executor.cc:156 onnxruntime::SequentialExecutor::Execute] Begin execution
2020-12-08 14:07:36.4106464 [E:onnxruntime:, sequential_executor.cc:318 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running MatMul node. Name:'MatMul_2533' Status Message: 
D:\5\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1736)\onnxruntime.dll!00007FFFB08C7273: (caller: 00007FFFB08C6FE8) Exception(1) tid(65d0) 80070057 The parameter is incorrect.
```
Both CPU and CUDA providers succeed with the model and varying input sizes. 
I am using the C++ API.

**Urgency**
Low, we can fallback to CPU and CUDA for the time being.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- ONNX Runtime installed from (source or binary): binary 1.5.2
- ONNX Runtime version: Microsoft.ML.OnnxRuntime.DirectML 1.5.2
- Python version: N/A
- Visual Studio version (if applicable): VS 2019
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: RTX2070 Super

**To Reproduce**
- Load and execute a session with [GPT-2-LM-Head](https://github.com/onnx/models/blob/master/text/machine_comprehension/gpt-2/model/gpt2-lm-head-10.onnx) 
- Confirm inference works for input `input1: [3792, 428, 262, 1103, 1517, 393, 318, 428]`
- Confirm the error appears for input `input1: [3792, 428, 262, 1103, 1517, 393, 318, 428, 655]` or `input1: [3792, 428, 262, 1103, 1517, 393, 318]` (length 9 and 7 respectively).

**Expected behavior**
The inference is performed without error and populates the output.

**Additional context**
GPT-2-LM-HEAD is using Onnx Version 1.6, so is expected to work with DirectML.

**Comment by wchao1115** [comment]
@hendrik-skubch Thanks for the report. We'll look into this. The MatMul_2533 node in the graph looks pretty standard to me. We'll look at it in more detail.

**Comment by wchao1115** [comment]
Hey @hendrik-skubch,

We think that the `matmul` part of the model is broken. What tool do you use to convert the model to ONNX? 

More specifically, the 2 inputs of `matmul` are of shapes [1,1,1,768] and [768,50257], which must produce a tensor of shape [1,1,1,50257] and not [1,1,8,50257]. When you use the DirectML backend, it flags that the output of the operator is defined as an incorrect shape causing the model to fail. This check is missing when you use ORT on the CPU, which is on itself also a bug. We haven't checked what the behavior is on the CUDA backend, but thought that it's probably the same as in the CPU code path.

**Comment by hendrik-skubch** [comment]
Interesting! I haven't converted the model myself, I grabbed it directly from https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2 for this test.

**Comment by sumitsays** [comment]
Hey @hendrik-skubch 
We have fixed the model and updated the ONNX Model Zoo repo. Please feel free to use this updated version of the model.
https://github.com/onnx/models/tree/master/text/machine_comprehension/gpt-2/model

**Comment by hendrik-skubch** [comment]
Great! Thank you, @sumitsays!
Unfortunately, I still get an error with the updated model:
```
2021-04-19 09:50:35.9708248 [E:onnxruntime:, sequential_executor.cc:339 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running Gather node. Name:'Gather_27' Status Message: D:\3\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1540)\onnxruntime.dll!00007FFD5C6F69E1: (caller: 00007FFD5C6F5ED0) Exception(3) tid(69c8) 80070057 The parameter is incorrect.
```
This is with Microsoft.ML.OnnxRuntime.DirectML 1.7.0.

It seems there is another issue?

**Comment by sumitsays** [comment]
Hi @hendrik-skubch ,
The model is working with v1.7.0 for me.

**Comment by hendrik-skubch** [comment]
Hi @sumitsays 
Thank you for checking! In that case I am probably unintentionally violating some assumption.


Here is a minimal example that produces this error message for me:

```
#include <cassert>
#include <cstdlib>
#include <iostream>
#include <limits>

#include <dml_provider_factory.h>
#include <onnxruntime_c_api.h>
#include <onnxruntime_cxx_api.h>

int main()
{
    OrtThreadingOptions* threading_options{nullptr};
    Ort::ThrowOnError(Ort::GetApi().CreateThreadingOptions(&threading_options));
    Ort::ThrowOnError(Ort::GetApi().SetGlobalIntraOpNumThreads(threading_options, 1));
    Ort::ThrowOnError(Ort::GetApi().SetGlobalInterOpNumThreads(threading_options, 1));
    assert(threading_options != nullptr);
    Ort::Env env(threading_options, ORT_LOGGING_LEVEL_VERBOSE, "test");

    Ort::SessionOptions session_options;
    session_options.DisablePerSessionThreads();
    session_options.SetExecutionMode(ORT_SEQUENTIAL);

    //session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_ENABLE_EXTENDED);
    session_options.SetGraphOptimizationLevel(GraphOptimizationLevel::ORT_DISABLE_ALL);
    //Disable the next line to run on cpu:
    Ort::ThrowOnError(OrtSessionOptionsAppendExecutionProvider_DML(session_options, 0));
    const wchar_t* model_path = L"data/gpt2/gpt2-lm-head-10.onnx";

    {
        Ort::Session session(env, model_path, session_options);

        Ort::AllocatorWithDefaultOptions allocator;

        const char* input_name = "input1";
        std::vector<int64_t> input_tensor_values{3792, 428, 262, 1103, 1517, 393, 318, 428, 655};

        int64_t input_tensor_size = input_tensor_values.size();
        std::vector<int64_t> input_node_dims{1, 1, input_tensor_size};

        const char* output_name = "output1";

        // create input tensor object from data values
        auto memory_info = Ort::MemoryInfo::CreateCpu(OrtArenaAllocator, OrtMemTypeDefault);
        Ort::Value input_tensor =
            Ort::Value::CreateTensor<int64_t>(memory_info, input_tensor_values.data(),
                input_tensor_size, input_node_dims.data(), input_node_dims.size());
        assert(input_tensor.IsTensor());

        // score model & input tensor, get back output tensor
        Ort::RunOptions ropts;
        ropts.SetRunLogVerbosityLevel(ORT_LOGGING_LEVEL_VERBOSE);

        auto output_tensors = session.Run(ropts, &input_name, &input_tensor, 1, &output_name, 1);

        assert(output_tensors.size() == 1 && output_tensors.front().IsTensor());

        Ort::TensorTypeAndShapeInfo shape = output_tensors.front().GetTensorTypeAndShapeInfo();
        std::vector<int64_t> result_shape = shape.GetShape();
        for (int64_t v : result_shape) {
            std::cout << "Result shape: " << v << std::endl;
        }
        float* float_ptr = output_tensors.front().GetTensorMutableData<float>();

        float maxv = std::numeric_limits<float>::lowest();
        int max_idx = -1;
        const int64_t vocab_size = 50257;
        for (int i = 0; i < 50257; ++i) {
            const float v = float_ptr[(input_tensor_size - 1) * vocab_size + i];
            if (v > maxv) {
                maxv = v;
                max_idx = i;
            }
        }
        std::cout << "Best: " << max_idx << " V: " << maxv << std::endl;
    }
    Ort::GetApi().ReleaseThreadingOptions(threading_options);
    std::cout << "Done." << std::endl;
    return 0;
}
```
If I do not register the dml provider, the example runs fine.

**Comment by hendrik-skubch** [comment]
I get the same issue with Microsoft.ML.OnnxRuntime.DirectML 1.8.0

**Comment by hendrik-skubch** [comment]
@sumitsays, would you mind providing a working C++/C example, if 1.7.0 works for you? The would be greatly appreciated.

**Comment by hendrik-skubch** [comment]
I also adopted the code at https://github.com/microsoft/onnxruntime/blob/master/samples/c_cxx/fns_candy_style_transfer/fns_candy_style_transfer.c to use GPT-2-LM-Head and a int64_t tensor as input, with the same result, Gather_27 is deemed invalid for some reason.

**Comment by hendrik-skubch** [comment]
Still experience this problem with  Microsoft.ML.OnnxRuntime.DirectML 1.11.0, however on a different node:

```
2022-04-19 18:11:03.6856732 [I:onnxruntime:, inference_session.cc:1576 onnxruntime::InferenceSession::Initialize] Session successfully initialized.
2022-04-19 18:11:03.8416719 [I:onnxruntime:, sequential_executor.cc:172 onnxruntime::SequentialExecutor::Execute] Begin execution
2022-04-19 18:11:03.8897490 [E:onnxruntime:, sequential_executor.cc:364 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running ReduceMean node. Name:'ReduceMean_32' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(1660)\onnxruntime.dll!00007FF852026310: (caller: 00007FF852025824) Exception(3) tid(6e38) 80070057 The parameter is incorrect.
```

**Comment by Coice** [comment]
@hendrik-skubch Did you ever resolve this? I am having the same issue.

**Comment by hendrik-skubch** [comment]
No, this is still an issue, unfortunately.

**Comment by Coice** [comment]
@hendrik-skubch I was able to resolve my issue by taking the directml.dll from the C# nuget directml package and placing that in the same folder as the onnxruntime.dll. This dll is not included in the release zip for dml and if you are working in c/c++ you will totally miss this requirement. If you don’t include the dll in your runtime directory, it ends up using the system version that is out of date, which loads your model, but fails with an obscure error during inference. Give this a shot if you haven’t already, hopefully it helps you or someone out there.

**Comment by hendrik-skubch** [comment]
Well, what do you know, that fixed it! Thank you @Coice, that was of great help!

**Comment by nums11** [comment]
Closing as fixed.
