### ISSUE TITLE
Build error: Payload contains two or more files with the same destination path

### ISSUE THREAD

**Issue by hig-dev** [microsoft/onnxruntime#6249]
**Description**
I would like to try to use the new Microsoft.AI.MachineLearning NuGet (1.6.0) but I am experiencing the following build error when I add the NuGet to my UWP project. I don't have this problem with the previous version (1.5.2).

Build configuration: Debug | x64
```
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: Payload contains two or more files with the same destination path 'Microsoft.AI.MachineLearning.dll', but they are different sizes. Source files: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: C:\Users\hig\.nuget\packages\microsoft.ai.machinelearning\1.6.0\build\uap\..\..\runtimes\win-x64\uap\Microsoft.AI.MachineLearning.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: C:\Users\hig\.nuget\packages\microsoft.ai.machinelearning\1.6.0\runtimes\win-x64\native\static\microsoft.ai.machinelearning.dll 
```

The target of my app is Build 19041 and the min version is Build 18362 and I am using the latest Visual Studio 16.8.3. 

**Urgency**
I would like to test the new version in order to close #5389.

**System information**
- OS Platform and Distribution: Windows 10 x64 (20H2) (Build 19042)
- ONNX Runtime installed from (source or binary): NuGet
- ONNX Runtime version: 1.6.0
- Visual Studio version: 16.8.3

**To Reproduce**
- Create a UWP project that targets Build 19041
- Add Microsoft.AI.MachineLearning NuGet (1.6.0)
- Build for Debug | x64

**Expected behavior**
The build runs without errors.

**Comment by hig-dev** [comment]
Can we get an update on this issue?
This issue basically prevents the usage of 1.6.0 in any UWP C# project.

I made the smallest possible sample project that reproduces the error.

Just try to build in using Debug | x64:
[issue6249sample.zip](https://github.com/microsoft/onnxruntime/files/5860598/issue6249sample.zip)

**Comment by EpsiRho** [comment]
I'm currently having the same issue and it is currently preventing me in using any model made with the Model Builder, since it outputs as a 1.6 .onnx.

**Comment by smk2007** [comment]
Hi,

Thanks for reporting this.

We are aware of the issue in the NuGet package layout that is causing multiple versions of the same dll to be simultaneously bin placed.

We are actively working on this issue!

**Comment by seagp-sato** [comment]
I installed version 1.7.0 via nuget and I get the same error.

**Comment by hig-dev** [comment]
> I installed version 1.7.0 via nuget and I get the same error.

Yes, it seems that the error has not been fixed.
```
1>  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: Payload contains two or more files with the same destination path 'Microsoft.AI.MachineLearning.dll', but they are different sizes. Source files: 
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: C:\Users\hig\.nuget\packages\microsoft.ai.machinelearning\1.7.0\build\uap\..\..\runtimes\win-x64\uap\Microsoft.AI.MachineLearning.dll
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6140,5): error APPX1111: C:\Users\hig\.nuget\packages\microsoft.ai.machinelearning\1.7.0\runtimes\win-x64\native\static\microsoft.ai.machinelearning.dll
```

**Comment by smk2007** [comment]
Unfortunately, this fix did not make it into the 1.7.0 release.

It has been fixed in master. The fix should become available in the next release.

**Comment by seagp-sato** [comment]
I see. Thank you for taking the trouble.
Try to wait for the next release.

**Comment by TheDuQe** [comment]
A NetStandard project referenced in Universal Windows platform WinUI project, I get the same error. Highly frustrating, I must now revert. I've always loved the way Microsoft Dotnet evolved since 2001 , but it looses day after day its legendary documented reliability. It becomes the same jungle like everlasting Java's profits and loss.

**Comment by hig-dev** [comment]
I checked the new 1.8.0 release and this problem is now fixed. Thanks.

**Comment by ebroglio** [comment]
This issue is back in version 1.10.0. Version 1.9.1 is fine.

**Comment by smk2007** [comment]
Hi, thank you for reporting this issue.

I created blank UWP applications in C++ and C# in VS2019 and VS2022 and was not able to reproduce the issue.
Have you tried a clean build?

Thanks,

**Comment by ebroglio** [comment]
yes, I tried. This is the error I get: 
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6151,5): error APPX1111: Payload contains two or more files with the same destination path 'microsoft.ai.machinelearning.dll', but they are different sizes. Source files: 
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6151,5): error APPX1111: C:\Users\stefa\.nuget\packages\microsoft.ai.machinelearning\1.10.0\runtimes\win-x64\lib\uap10.0\microsoft.ai.machinelearning.dll
2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(6151,5): error APPX1111: C:\Users\stefa\.nuget\packages\microsoft.ai.machinelearning\1.10.0\runtimes\win-x64\_native\microsoft.ai.machinelearning.dll

Going back to 1.9.1 and the problem is gone.

**Comment by smk2007** [comment]
I see it now. Happens on build. I'll take a look.

**Comment by smk2007** [comment]
This has been resolved in master with this change: https://github.com/microsoft/onnxruntime/pull/10076
A build from source version of the NuGet package can be built by using the following build.bat parameters:

--enable_wcos
--ms_experimental
--use_dml
--use_winml
--build
--build_nuget

**Comment by SuavePirate** [comment]
Confirming this in 1.12.1

**Comment by Walia8416** [comment]
How do i resolve this issue?

**Comment by tom-huntington** [comment]
I'm also getting this in a WinUI3 app

**Comment by tom-huntington** [comment]
@smk2007 would it be possible to get something working for WinUI3. I've waiting on this sometime https://github.com/microsoft/onnxruntime/issues/14915

Maybe I could manually copy across the dll, and add the header directory.

**Comment by smk2007** [comment]
@juwens, @SuavePirate , @Walia8416,  @tom-huntington - 
From what I can gather, there is an issue with adding the Microsoft.AI.MachineLearning NuGet Package across various versions (1.10, 1.11, 1.12).

However, I am unable to repro this problem in VS2022 with the latest Microsoft.AI.MachineLearning NuGet package (1.15.1).
I have tried the following project templates:
  - C# Blank App (Universal Windows)
  - C# Blank App, Packaged (WinUI 3 in Desktop)
  - C# Console App with <TargetFramework>net7.0-windows10.0.19041.0</TargetFramework>
  - Blank App (C++/WinRT) UWP
  - Windows Console Application (C++/WinRT)
  - C++ Console App
  
  Can you please share your configuration that is currently causing problems?
  
@tom-huntington,
Regarding the C# Blank App, Packaged (WinUI 3 in Desktop), I have created the following PR ( https://github.com/microsoft/onnxruntime/pull/16415) to address the issue.
If you would like to verify that this works with your applications feel free to checkout the branch in the PR and run a local build.

These parameters will be needed to produce a local package to verify.
--enable_wcos
--ms_experimental
--use_dml
--use_winml
--build
--build_nuget

**Comment by tom-huntington** [comment]
> @tom-huntington, Regarding the C# Blank App, Packaged (WinUI 3 in Desktop), I have created the following PR ( #16415) to address the issue.

I patched the `.tagrets` file locally, and now it builds. Thanks!

**Comment by nums11** [comment]
Closing as fixed.
