### ISSUE TITLE
Several failing tests with CUDA execution provider

### ISSUE THREAD

**Issue by dllu** [microsoft/onnxruntime#8972]
**Describe the bug**

```
[ RUN      ] AttentionTest.AttentionPastState_dynamic
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:241: Failure
The difference between expected[i] and output[i] is 0.0053014755249023438, which exceeds threshold, where
expected[i] evaluates to 2.3628411293029785,
output[i] evaluates to 2.3681426048278809, and
threshold evaluates to 0.004999999888241291.
i:2337, provider_type: CUDAExecutionProvider
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/common/tensor_op_test_utils.cc:14: ORT test random seed: 168722168
[  FAILED  ] AttentionTest.AttentionPastState_dynamic (27 ms)
```

```
[ RUN      ] EmbedLayerNormTest.EmbedLayerNormBatch1_Float16
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to 0.369140625,
f_output[i] evaluates to inf, and
threshold evaluates to 0.004999999888241291.
i:0, provider_type: CUDAExecutionProvider
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to 0.061492919921875,
f_output[i] evaluates to inf, and
threshold evaluates to 0.004999999888241291.
i:1, provider_type: CUDAExecutionProvider
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to 1.16015625,
f_output[i] evaluates to inf, and
threshold evaluates to 0.004999999888241291.
i:2, provider_type: CUDAExecutionProvider
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to -0.85107421875,
f_output[i] evaluates to -inf, and
threshold evaluates to 0.004999999888241291.
i:3, provider_type: CUDAExecutionProvider
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to 0.7431640625,
f_output[i] evaluates to inf, and
threshold evaluates to 0.004999999888241291.
i:4, provider_type: CUDAExecutionProvider
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to -0.05743408203125,
f_output[i] evaluates to inf, and
threshold evaluates to 0.004999999888241291.
i:5, provider_type: CUDAExecutionProvider
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to 0.84326171875,
f_output[i] evaluates to inf, and
threshold evaluates to 0.004999999888241291.
i:6, provider_type: CUDAExecutionProvider
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:302: Failure
The difference between f_expected[i] and f_output[i] is inf, which exceeds threshold, where
f_expected[i] evaluates to -0.8515625,
f_output[i] evaluates to -inf, and
threshold evaluates to 0.004999999888241291.
i:7, provider_type: CUDAExecutionProvider
[  FAILED  ] EmbedLayerNormTest.EmbedLayerNormBatch1_Float16 (2 ms)
```

```
[ RUN      ] CastOpTest.NonStringTypes
2021-09-05 19:58:28.223942426 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.223956046 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 9 to type 16
2021-09-05 19:58:28.248229803 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.248242393 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 1 to type 16
2021-09-05 19:58:28.272987298 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.273001528 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 11 to type 16
2021-09-05 19:58:28.298147831 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.298160491 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 2 to type 16
2021-09-05 19:58:28.323433153 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.323445933 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 4 to type 16
2021-09-05 19:58:28.348965155 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.348978025 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 12 to type 16
2021-09-05 19:58:28.374147238 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.374159698 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 13 to type 16
2021-09-05 19:58:28.398991163 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.399003663 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 3 to type 16
2021-09-05 19:58:28.423634528 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.423646918 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 5 to type 16
2021-09-05 19:58:28.448329064 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.448342073 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 6 to type 16
2021-09-05 19:58:28.472979909 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.472992579 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 7 to type 16
2021-09-05 19:58:28.498332201 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.498344881 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 10 to type 16
2021-09-05 19:58:28.500363231 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.500375411 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 9
2021-09-05 19:58:28.502375301 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.502387471 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 1
2021-09-05 19:58:28.504419391 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.504431471 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 11
2021-09-05 19:58:28.506445190 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.506457290 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 2
2021-09-05 19:58:28.508461760 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.508473660 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 4
2021-09-05 19:58:28.510545469 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.510557529 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 12
2021-09-05 19:58:28.512570859 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.512582839 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 13
2021-09-05 19:58:28.514601509 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.514613529 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 3
2021-09-05 19:58:28.516633609 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.516645599 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 5
2021-09-05 19:58:28.518658619 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.518670399 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 6
2021-09-05 19:58:28.520679668 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.520691698 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 7
2021-09-05 19:58:28.522733428 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.522745488 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 10
2021-09-05 19:58:28.524745078 [E:onnxruntime:Cast:Cast, sequential_executor.cc:346 Execute] Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
2021-09-05 19:58:28.524756928 [E:onnxruntime:Default, provider_test_utils.cc:817 ExecuteModel] Run failed with status: Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:819: Failure
Value of: status.IsOK()
  Actual: false
Expected: true
Non-zero status code returned while running Cast node. Name:'node1' Status Message: CUDA error cudaErrorInvalidDeviceFunction:invalid device function
Google Test trace:
/home/dllu/builds/onnxruntime/onnxruntime/test/providers/cpu/tensor/cast_op_test.cc:96: Cast from type 16 to type 16
[  FAILED  ] CastOpTest.NonStringTypes (326 ms)
```

**Urgency**
If there are particular important use cases blocked by this or strict project-related timelines, please share more information and dates. If there are no hard deadlines, please specify none.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Arch Linux
- ONNX Runtime installed from (source or binary): Source
- ONNX Runtime version: master`60c98a86b7f0deb2bbb9f9ca8ab5d14e2fc383e7
- Python version: 3.9.6
- Visual Studio version (if applicable): n/a
- GCC/Compiler version (if compiling from source): 11.1.0
- CUDA/cuDNN version: 11.4
- GPU model and memory: NVIDIA Geforce RTX 3090

**To Reproduce**
I just ran:

```
/build.sh --use_cuda --cudnn_home /usr/ --cuda_home /opt/cuda/ --config RelWithDebInfo --parallel --build_shared_lib
```

**Expected behavior**

All test should pass.

**Screenshots**

**Additional context**

**Comment by snnn** [comment]
As a workaround, change you build command to
```
/build.sh --use_cuda --cudnn_home /usr/ --cuda_home /opt/cuda/ --config RelWithDebInfo --parallel --build_shared_lib
--cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=52
```
Please update the number(52), make it match to your GPU card. See https://developer.nvidia.com/cuda-gpus

**Comment by snnn** [comment]
Also, you may try this change: #8793

**Comment by snnn** [comment]
We merged the fix. Could you try it again?  You don't need to change anything, just pull the last master and run the same command again.

**Comment by dllu** [comment]
Hmm still getting the test failure:
```
[ RUN      ] AttentionTest.AttentionPastState_dynamic
/home/user/builds/onnxruntime/onnxruntime/test/providers/provider_test_utils.cc:241: Failure
The difference between expected[i] and output[i] is 0.0050199031829833984, which exceeds threshold, where
expected[i] evaluates to -2.7983651161193848,
output[i] evaluates to -2.8033850193023682, and
threshold evaluates to 0.004999999888241291.
i:772, provider_type: CUDAExecutionProvider
Google Test trace:
/home/user/builds/onnxruntime/onnxruntime/test/common/tensor_op_test_utils.cc:14: ORT test random seed: 4132595390
[  FAILED  ] AttentionTest.AttentionPastState_dynamic (32 ms)
```

This is on 2e8792ca42413df5e9fb686387c6a1e7f755bc7d.

I also tested this on a brand new machine with Ubuntu 20.04 and NVIDIA GeForce RTX 3090, driver 470.63.01, CUDA 11.4, and am getting the exact same problem. The failure can also be replicated consistently across multiple runs with different ORT test random seeds.

However the other two failures in my original issue seem to have been fixed :thinking:

**Comment by snnn** [comment]
What if you add "--cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=86" to your build command for the GeForce RTX 3090 ? Honestly speaking, I haven't test the code on that card. If there is any test failure, I wouldn't be surprised.

**Comment by dllu** [comment]
I tried that too, the failure persists even after I add `--cmake_extra_defines CMAKE_CUDA_ARCHITECTURES=86`.

**Comment by snnn** [comment]
Is it the only failure? 

@yufenglee, could you please take a look?

**Comment by dllu** [comment]
I think `CApiTestGlobalThreadPoolsWithProvider` is also failing:

```
/home/user/builds/onnxruntime/onnxruntime/test/global_thread_pools/test_inference.cc:59: Failure
The difference between values_y[i] and f[i] is 3.7252902984619141e-06, which exceeds 1e-6f, where
values_y[i] evaluates to 0.0038459999486804008,
f[i] evaluates to 0.0038422746583819389, and
1e-6f evaluates to 9.9999999747524271e-07.
[  FAILED  ] CApiTestGlobalThreadPoolsWithProviders/CApiTestGlobalThreadPoolsWithProvider.simple3/1, where GetParam() = 1 (113 ms)
```

**Comment by snnn** [comment]
Looks good. Welcome to open a pull request and contribute the changes.

**Comment by DXZDXZ** [comment]
I also have the same problem (AttentionTest.AttentionPastState_dynamic) on GPU 3090.
