### ISSUE TITLE
Problem with include in provider_options.h

### ISSUE THREAD

**Issue by TejasT** [microsoft/onnxruntime#9148]
Faced an issue while using onnxruntime-gpu on Visual Studio using nuget installation:

**System used:**
Windows 10
(Not a GPU/CUDA specific issue)

**Issue faced:**
cuda_provider_factory.h has an include #include "core/framework/provider_options.h", while all header files are placed in a single folder after installation. 

**Fix:**
For me, changing #include "core/framework/provider_options.h" to #include "provider_options.h" worked. 

Shouldn't this be taken care of by Visual studio/onnxruntime nuget package itself?

**Comment by jywu-msft** [comment]
this should be fixed in upcoming ORT 1.9 release. cuda_provider_factory.h is no longer included with nuget package and OrtSessionOptionsAppendExecutionProvider_CUDA moved to C api header.

**Comment by TejasT** [comment]
Yes now it works fine. There is one more problem though, I think this might be related to nuget package; **including header files is still not possible without including the path in "Additional Include Directories"** in a visual studio project where onnxruntime-gpu is installed through nuget package manager.
